### ISSUE TITLE
communication lost : link down

### ISSUE THREAD

**Issue by HowardChoi74** [mavlink/mavlink#1016]
Hi i am Howard who begin to program mavros.
When I do arming(arm throttle) in mode Manual / Stabilize, suddenly link down and link 1 OK heatbeat ok.
It was worked good but one day, it has a problem. QGC also do not work when I switch the button to arming. I do reinstall firmware and sensor calibration but nothing changed. before this issue, I have a mag sensor inconsistant and mag 0 : fail time out....
What happen to me? is this hardware issue or do I  miss sth?
please give me any advice regarding of this issue.
thanks for considering me.

**Comment by hamishwillee** [comment]
YOu've asked a firmware specific question about using the ROS system on the mavlink site. Ie completely the wrong place. 
YOu need to raise the question in the right place - depending on your flight stack, use one of the forums linked from here: https://github.com/mavlink/mavros#support-forums-and-chats
