### ISSUE TITLE
Does COMMAND_ACK use MAV_RESULT or MAV_CMD_ACK?

### ISSUE THREAD

**Issue by Susurrus** [mavlink/mavlink#105]
Right now `COMMAND_LONG` messages should be responded to with a value from the MAV_RESULT enum according to the documentation in common.xml. But then what does MAV_CMD_ACK do? As QGC only uses `MAV_RESULT`, should that other enum be deleted? If it should be deleted, should `MAV_RESULT` be renamed to `MAV_CMD_RESULT` to be more clear?

**Comment by AviointicsCzar** [comment]
why was this topic closed?
