### ISSUE TITLE
Additional param metadata

### ISSUE THREAD

**Issue by hamishwillee** [mavlink/mavlink#1050]
Don, we're starting to use the param metadata in some real cases. Gus made some points about particular cases that might not be as useful as we hope for display in UI. Would appreciate your thoughts:

1. Example below is actually a boolean. Do we need a way to represent that, and how would that be done best?
    `<param index="2" label="Confirm Request" minValue="0" maxValue="1">0: No action 1: Format storage</param>`
2. In fact if you're sending the message you would always specify `1`. I tend to think we need `default` too. Thoughts?
3. A lot of params are reserved. My thinking is that if we're going to do this in descriptions we should do it via markup. HOWEVER, I'd rather we made an explicit statement that any param that is not declared is automatically assumed to be reserved and we generate whatever code is needed to support that (deleting any things we have currently declared as reserved "manually").

**Comment by dogmaphobic** [comment]
I'm not sure I understand these instances where you need a confirmation parameter (1 to confirm, 0 to ignore). Wouldn't _not_ sending the command be simpler? :)

**Comment by DonLakeFlyer** [comment]
> nanUnchanged bool false True: value can be set to NaN to signal unchanged

If this is true the QGC will show an entry field with a checkbox. You can see an example of it with the Heading field of a waypoint:
![screen shot 2019-01-07 at 1 29 28 pm](https://user-images.githubusercontent.com/5876851/50794567-51437500-1280-11e9-8d9a-a4a5c1f18e43.png)

This is because there is no reasonable way for an end user to enter a NaN into a numeric field. Nor should they have to understand that NaN means, leave the heading alone.

**Comment by hamishwillee** [comment]
> I'm not sure I understand these instances where you need a confirmation parameter (1 to confirm, 0 to ignore). Wouldn't not sending the command be simpler? :)

Yes. It is madness, but a lot of messages do this. Worse, then you need to add other options, and those don't make sense in the context of the original options.
I don't think bool in this case actually helps. I like the idea, but lets park until we find a case where we actually need it. 

In future, let's make sure that we don't have such annoying design.

**Comment by hamishwillee** [comment]
@DonLakeFlyer But I still think params could use a default, and it looks like you support them, right?

**Comment by hamishwillee** [comment]
With respect to "eserved", I think your point in https://github.com/mavlink/mavlink/issues/1050#issuecomment-452086899 is that a reserved parameter needs to send a value that can be interpreted as "not used" when the param is implemented. 

That way the recipient does not need to know whether the GCS doesn't implement the param (ie believes it is reserved) or is implementing it and saying "not supported". 

Is that right?

I'm having trouble wrapping my head around why using NaN would be a problem in any case for reserved values.

What if the message is sent in a COMMAND_INT where NaN doesn't make sense?

**Comment by DonLakeFlyer** [comment]
> that a reserved parameter needs to send a value that can be interpreted as "not used" when the param is implemented

> Is that right?

> What if the message is sent in a COMMAND_INT where NaN doesn't make sense?

Command int param 1-4 are still floats.

**Comment by hamishwillee** [comment]
@DonLakeFlyer Thanks, but that didn't answer my outstanding questions.
Let me restructure for easier digestion:

On reserved:

1. I think your point is that a reserved parameter needs to send a value that can be interpreted as "not used" whether or not the param is reserved. That way the recipient does not need to know whether the GCS is sending a "nothing" value (reserved) or a "do nothing" (not reserved but not requiring action)
   - Is that right?
   - Why wouldn't sending NaN always be right for params 1-4, 7? This is never going to be a number
   - param 5 and param 6 can be sent as either int or as float, depending on the message. So is it correct to say that for param 5 and param 6 a reserved message *must* have a default value of zero? (ie it can't even be UINT32_MAX because that will be unhelpful if message is sent in a COMMAND_LONG)
   - Can we expect a GUI to know this or must we explicitly define params and give them this default? 
   -  Is there any difference between reserved and empty?

If I get this, then it seems to me that if a param is not defined then the GCS can assume it is reserved/empty and not display it. For the purposes of sending it should use NaN for params 1,2,3,4,7 and 0 for param 5 and 6. IF some other value needs to be set, then a param could be explicitly be defined and that would have to have a `default` or `nanUnchanged` set if it wanted different behaviour.

Does that make sense?

And further:
1. Do you want me to add support for `default` and `nanUnchanged` to the schema?
1. The definition of `nanUnchanged` only covers the case (defines a default value) where `nanUnchanged` is true (ie it is Nan). What is the default value if `nanUnchanged` is false?

**Comment by DonLakeFlyer** [comment]
Here are the various problems with reserved values:
* The previous spec said nothing about them, but in general I think most GCS would send them as 0
* QGC sets reserved params to 0 unless otherwise specified by a default. I think MP is the same.
* As far as I know MP ui is not capable of entering/defaulting a NaN in a param. I could be wrong here.
* If a param is reserved and set to 0 and then later that param is used for a real value you have to be careful that the value 0 works correctly in all cases. Same goes for NaN. For example lets say that the reserved param was set to 0. And you now want to use that param for a heading value where NaN means unchanged. You can't because 0 will be interpreted as a real heading as opposed to "I didn't implement this".

> 1. Do you want me to add support for `default` and `nanUnchanged` to the schema?

That's up to you. It depends on what is trying to be achieved by this. If it is just to spec the schema then not needed. If it is to provide enough information for a GCS to automate building ui for a mission item then it is needed.

> 2\. The definition of `nanUnchanged` only covers the case (defines a default value) where `nanUnchanged` is true (ie it is Nan). What is the default value if `nanUnchanged` is false?

If nanUnchanged = false then a separate default value can be optionally specified in the schema.

**Comment by DonLakeFlyer** [comment]
Also for completeness this is the json data which QGC uses for details on aMAV_CMD:
```
/// UI Information associated with a mission command (MAV_CMD)
///
/// MissionCommandUIInfo is used to automatically generate editing ui for a MAV_CMD. This object also supports the concept of only having a set of partial
/// information for the command. This is used to create overrides of the base command information. For on override just specify the keys you want to modify
/// from the base command ui info. To override param ui info you must specify the entire MissionParamInfo object.
///
/// The json format for a MissionCommandUIInfo object is:
///
/// Key                     Type    Default     Description
/// id                      int     reauired    MAV_CMD id
/// comment                 string              Used to add a comment
/// rawName                 string  required    MAV_CMD enum name, should only be set of base tree information
/// friendlyName            string  rawName     Short description of command
/// description             string              Long description of command
/// specifiesCoordinate     bool    false       true: Command specifies a lat/lon/alt coordinate
/// specifiesAltitudeOnly   bool    false       true: Command specifies an altitude only (no coordinate)
/// standaloneCoordinate    bool    false       true: Vehicle does not fly through coordinate associated with command (exampl: ROI)
/// friendlyEdit            bool    false       true: Command supports friendly editing dialog, false: Command supports 'Show all values" style editing only
/// category                string  Advanced    Category which this command belongs to
/// paramRemove             string              Used by an override to remove params, example: "1,3" will remove params 1 and 3 on the override
/// param[1-7]              object              MissionCommandParamInfo object
///
```

**Comment by DonLakeFlyer** [comment]
And here is the json for the base of the MAV_CMD tree which QGC uses: https://github.com/mavlink/qgroundcontrol/blob/master/src/MissionManager/MavCmdInfoCommon.json

**Comment by dogmaphobic** [comment]
I see a distinction between commands that are presented to the user (UI) and those that exclusively used programmatically (never presented within the UI). Something like:

- MAV_CMD_REQUEST_AUTOPILOT_CAPABILITIES
- MAV_CMD_REQUEST_CAMERA_INFORMATION
- MAV_CMD_REQUEST_CAMERA_SETTINGS
- MAV_CMD_REQUEST_STORAGE_INFORMATION
- MAV_CMD_REQUEST_FLIGHT_INFORMATION

And dozen of other commands are never used from an "UI". The requirement for metadata is different. For these commands above, it only matters for documentation on how to implement them and use them.

@DonLakeFlyer for mission commands, where do you pull the metadata from? You mentioned a Json file above. Where does it come from?

**Comment by DonLakeFlyer** [comment]
That is correct. Not all commands need to have ui metadata. The json files in QGC are built by hand by me by pawing through the firmware source to figure what is supported and how. They are actually a hierarchy of json files which form a tree with the leaves of the tree being specific to a firmware and vehicle type. I linked to the json file above for the base of the tree which is the mavlink generic representation of the command. This allows QGC to adjust MAV_CMD usage such that you can hide params for specific vehicle/firmware combinations and or override settings for specific vehicle/firmwrae combinations.

**Comment by dogmaphobic** [comment]
> The json files in QGC are built by hand by me by pawing through the firmware source to figure what is supported and how.

That's what I thought. @hamishwillee is talking about the metadata present in the message definition XML files. I think this discussion is comparing apples to oranges.

**Comment by DonLakeFlyer** [comment]
I thought the idea was that if the mavlink metadata had enough information in it then a ground station wouldn't need to do what QGC does. Or at least some part of it. You still have the problem of firmware or vehicle specific changes.

**Comment by hamishwillee** [comment]
Thanks!

> I thought the idea was that if the mavlink metadata had enough information in it then a ground station wouldn't need to do what QGC does. Or at least some part of it. 

That is correct. So yes, I will add `default` and `nanUnchanged` to the schema.

Another way of putting this is that I want to capture as much of the intention of the messages as possible in metadata so that consumers/users can construct sensible UIs and send sensible values. Anything about values or ranges that is currently in the description should really be in metadata.

@dogmaphobic Yes, I appreciate that some messages won't need metadata for UI generation (and apologies of using your messages as a guinea pig while I seek to understand this). The metadata is optional, and should used where it is sensible to do so. For the non-UI commands you point to I would add `default` once it is in schema and set to 1 say for the normal action.

**Comment by dogmaphobic** [comment]
> The metadata is optional, and should used where it is sensible to do so. For the non-UI commands you point to I would probably just add `default` once it is in schema and set to 1.

Optional to a point. There are two aspects to it:

For UI creation in cases commands are used within the UI. This is mostly what this discussion is all about. For that to work properly, you would need to implement all the fields, type definition, long and short descriptions, etc. Don has manually created. Some may not be practical, in which case, QGC will continue to ignore all of it and continue using Don's own, manually created Json file.

The second is documentation. When the XML file is parsed and the HTML documentation page is created, it can use a lot of this metadata to properly flag and document these things (like the WIP flag, link to Enums, etc.) That's what I had in mind in the beginning of this discussion (and the source of my confusion).

**Comment by DonLakeFlyer** [comment]
I guess my concerns are two fold:
1) What I have described is something that works for QGC in relationship to the little item editors it creates. Not totally sure it's generic.
2) Even with this fully in the xml, it's still not enough for QGC to run from. The QGC metadata is a tree of this information which each level of the tree up to the leaves overriding the data below. I don't see any way to represent this rationally in mavlink.

**Comment by hamishwillee** [comment]
@dogmaphobic Yes.
- For UI creation, currently I presume the long description is the description field. How is short description determined?
- For docs, yes, I am trying to do the right thing here too. 

@DonLakeFlyer Most of this stuff looks generic to me. From a specification point of view this is all stuff that otherwise should be captured in the description (or there will be ambiguity). Having the metadata forces discipline in the documentation. 

The fact that this is not enough for QGC to build the full tree is annoying, but not as important to me as ensuring good specification of limits/reducing ambiguity. That said, anything we can do to help, I'm for.

**Comment by DonLakeFlyer** [comment]
The QGC mav_cmd metdata only has "friendName" and "description". Base of the tree for MAV_CMD_NAV_WAYPOINT as an example:
```
        {
            "id":                   16,
            "rawName":              "MAV_CMD_NAV_WAYPOINT",
            "friendlyName":         "Waypoint",
            "description":          "Travel to a position in 3D space.",
            "specifiesCoordinate":  true,
            "friendlyEdit":         true,
            "category":             "Basic",
            "param1": {
                "label":            "Hold",
                "units":            "secs",
                "default":          0,
                "decimalPlaces":    0
            },
            "param2": {
                "label":            "Acceptance",
                "units":            "m",
                "default":          3,
                "decimalPlaces":    2
            },
            "param3": {
                "label":            "PassThru",
                "units":            "m",
                "default":          0,
                "decimalPlaces":    2
            },
            "param4": {
                "label":            "Heading",
                "units":            "radians",
                "nanUnchanged":     true,
                "default":          null,
                "decimalPlaces":    2
            }
        },
```

UI where you can see them used:
![screen shot 2019-01-08 at 2 54 53 pm](https://user-images.githubusercontent.com/5876851/50863977-70f89d00-1355-11e9-87de-db0ec395c993.png)

**Comment by DonLakeFlyer** [comment]
The above example also shows the difference between the mavlink generic metadata (4 params) and then the fact that further out of the branches of the metadata tree the majority of the params have been removed (1 param showm).

**Comment by hamishwillee** [comment]
We could probably provide a friendlyname. 
A description is a bit tougher because it depends a bit on the context. We'll be a lot closer as we start to pull options into enums etc so that all this information doesn't have to be in the description.

**Comment by hamishwillee** [comment]
> With respect to reserved

Thanks for your comments in https://github.com/mavlink/mavlink/issues/1050#issuecomment-452389033

The current spec says nothing about them either. 
I want to change that before they become a (bigger) pain point.

The default value is a pain. I will document the implications, but I'm not sure what advice to offer - perhaps that if there is just one empty param then don't define it, but if there is more than one define one explicitly with value=NaN - that way you know you will have the option to redefine at least one of each type?

What I plan to do is:
- Delete all "Empty" and "Reserved" params. Currently these appear to me to be exactly the same. Since none of them have defaults - we're no worse off from this.
- Update toolchain to make sure that docs work OK with missing params
- Maybe update toolchain to prevent or warn on these being set. TBD.
- Add `reserved` flag to metadata, which is assumed false (or true if param index is not defined).

Then docs should be updated to reflect the status quo, and that includes the fact that we don't have any proper way of versioning changes (in particular in enums/MAV_CMDs)

So docs will say:
1. If a parameter is not needed/used in a command definition then it is considered *reserved*.
1. To make a param reserved you can either omit the parameter index definition or explicitly define a parameter as reserved; the difference is the default value send for the message (discussed below).
1. If a parameter index is not defined the parameter is implicitly reserved, and has the following properties:
   - The param value must be send as 0
   - UIs should not display the param.
1. A parameter may also be explicitly defined and marked as *reserved* by adding `reserved="true"` to the definition. This would be done in order to set a default value of `NaN` rather than zero (for reasons discussed below). E.g.:
   ```
   <param index="2" reserved="true" default="NaN" />
   ```

1. As discussed above, reserved params must always be sent with a (default) value of either 0 or NaN.
  
   The default value is **important** because it affects how you can reuse the param. If reusing a reserved param for a new message, the original default value must either mean "unchanged" or be *invalid* for the new parameter definition. Otherwise a receiving system has no way to know if the GCS is sending a valid instruction or is using the reserved definition.
   
   As an example, consider a reserved parameter with default value of 0 that is redefined for sending heading values. For the new message a value of 0 is valid. For this param, a reserved value with a default of NaN should have been used.

**Comment by hamishwillee** [comment]
@DonLakeFlyer Further to above, in https://github.com/mavlink/mavlink/pull/1060, @dogmaphobic specifies that all reserved params are NaN in the command description, though specifically in one or two cases he specifies 0:
```
      <entry value="531" name="MAV_CMD_SET_CAMERA_ZOOM">
        ...
        <description>Set camera zoom. Returns CAMERA_SETTINGS message. Use NaN for reserved values.</description>
        ...
        <param index="3">Reserved (all remaining params)</param>
      </entry>
```

My understanding is that QGC will default these to zero in all cases, because there is no automation to set NaN.

In post above I was proposing that if you wanted to have a default Nan param you would have to create these individually, and you can't set the param 5, 6 as NaN because these might be sent in ints. So to do the closes you can what Gus wants you would have to specify:
```
<param index="3" reserved="true" default="NaN" />
<param index="4" reserved="true" default="NaN" />
<param index="7" reserved="true" default="NaN" />
```
Does it make sense to have a MAV_CMD level metadata for specifying the default of all reserved items unless explicitly specified for are the 5,6, params that must be 0? i.e.

```
      <entry value="531" name="MAV_CMD_SET_CAMERA_ZOOM" reservedDefault="NaN">
```

**Comment by DonLakeFlyer** [comment]
> My understanding is that QGC will default these to zero in all cases, because there is no automation to set NaN.

By default QGC will set params it doesn't know about to 0. Unless you futz with the QGC json for the command and specifically call out the default as NaN.

I would use this variant in mavlink spec: ```<param index="3" reserved="true" default="NaN" />```

**Comment by DonLakeFlyer** [comment]
> Unless you futz with the QGC json for the command and specifically call out the default as NaN.

I'm wrong about this. There isn't currently a way in QGC to set reserved values to NaN only 0. In looking at the QGC code this type of variant `<entry value="531" name="MAV_CMD_SET_CAMERA_ZOOM" reservedDefault="NaN">` would actually be easier to implement. So there is only a single bool to control it at the command level. Sorry for getting it wrong.

**Comment by hamishwillee** [comment]
@DonLakeFlyer So just to confirm, you're saying that if I want to have a reserved param with default 0 I can just not-define the param, or I can define it as currently but not define reservedDefault.

However if I want to set any params as default NaN then I have to set all of them to that by default, and then I can set individual params back to zero:
```
<entry value="531" name="MAV_CMD_SET_CAMERA_ZOOM" reservedDefault="NaN"> 
<param index=1 reserved="true" default="0" />
```
1. Is that correct?
1. What about param 5 and 6, which may be INT? Do I need to explicitly set them as 0 anyway if I use `reservedDefault="NaN"`? For the user it would be easier if I could assume that these would be set to 0, but then with this scheme there would be no way to say "this message can only be sent as a command_long (ie no ints)" and I explicitly want these as NaN. 
1. Are there any other odd cases for defaults that we can't meet - ie I know that we might want to say do "default=3" for an enum, if there are a number of options (ie when not reserved)

**Comment by hamishwillee** [comment]
@DonLakeFlyer Ping - please see my clarification/question above.

**Comment by DonLakeFlyer** [comment]
I'm just talking from the standpoint of what QGC already supports from it's json format. Which is this case is none of what you describe. Therefore it's all new territory and can be anything not too crazy. In thinking some more about it, using this format: ```<param index=1 reserved="true" default="0" />``` would be better. With the something like the spec saying if the param is not specified, then it is assumed to be reserved and defaulted to 0.

**Comment by hamishwillee** [comment]
FYI, this is done or in progress
- Schema includes `reserved` and allows default of `0` or `NaN`.
- In source docs changes to support automated in-source docs of reserved  params in https://github.com/ArduPilot/pymavlink/pull/269
- Docs stating the default of reserved and default 0 for undefined params going in as part of https://github.com/mavlink/mavlink-devguide/pull/168

I'll set this closed because it is "in hand"
