### ISSUE TITLE
CI failing Python 3.3 tests due to lmxl 3.6 incompatibility

### ISSUE THREAD

**Issue by hamishwillee** [mavlink/mavlink#1051]
CI for Python 3.3 failing all PRs in the environment setup stage because "This lxml version requires Python 2.7, 3.4 or later.". Tests pass on 2.7 and 3.5. The version does not appear to have changed for sometime in ArduPilot/pymavlink, so no idea what is going on.

Failing example here: https://travis-ci.org/mavlink/mavlink/jobs/476173108#L432 (from https://github.com/mavlink/mavlink/pull/1048)

**Comment by dagar** [comment]
I'm not sure what to suggest, lxml dropped support for Python 3.3 in the current version (4.3.0). You could update the requirements.txt to specify a specific version of lxml.

![image](https://user-images.githubusercontent.com/84712/50774623-e8e59b00-1261-11e9-84b2-165142cfbcf9.png)




What are we trying to achieve with mavlink CI? If the requirement (or desire) is to test a wide range of python versions I'm wondering if we'd be better off leaning on docker for the environments.

**Comment by hamishwillee** [comment]
@amilcarlucas Thanks.

> What are we trying to achieve with mavlink CI? If the requirement (or desire) is to test a wide range of python versions I'm wondering if we'd be better off leaning on docker for the environments.

@dagar I've created #1056 to remove the Python 3.3 build from travis. We don't really need it to work on any particular version of Python because this is a build toolchain, not a runtime toolchain. As long as it runs on near recent Python 2 and 3 I'm OK (ideally the versions shipped with Ubuntu LTS)
