### ISSUE TITLE
Mavlink communication between Arduino UNO and Pixhawk Mini

### ISSUE THREAD

**Issue by ziimiin14** [mavlink/mavlink#1114]
I am currently using PX4 1.8.2 stable version for my Pixhawk Mini. I am able to read the data transmitted from Pixhawk Mini to Arduino Uno but sending command from Arduino Uno to Pixhawk Mini seems does not work for me. This causes me the problem to change from Loiter mode to Offboard mode using the RC. I just constantly getting the message, "Offboard Rejected". My code is attached below. Can anyone take a quick look what is happening because I believe that the Pixhawk MINI cannot receive the target setpoints from Arduino Uno and this causes the "Offboard Rejected" issues. I try to debug for many days but no luck for me. I am coming here for some suggestion if anyone knows what happens.

///////////////////////THIS IS MY CODE//////////////////////////////////
#include <SoftwareSerial.h>
SoftwareSerial pxSerial(9,10); // RX, TX
#include "mavlink.h"

// Mavlink variables

int target_system_id = 1;
int companion_id =20; // Arduino UNO id (I set it randomly from 1-255 except 1 since Pixhawk using 1)
int component_id = 1; // Can be 0 or 1? I just set 1.
int target_component_id = 1;

void setup() {
 Serial.begin(57600);
 pxSerial.begin(57600);

}
void loop() {
 mavlink_message_t msg;
 for(int x = 0; x<100; x++)
 {
 send_HB(msg);
 delay(100);
 Serial.println("Sending HeartBeat");
 }
 while(true)
 {
 //Serial.print("Time:");
 //Serial.println(current_time/1000);
 previous_time = current_time;

```
float velxx = 1.5;
set_Position(msg,velxx);
delay(100); // Setpoints sent run in 10Hz.

```

}

}
void send_HB(mavlink_message_t &msgg){
 int sysid = 20; ///< ID for my companion board
 int compid = 1 ; ///< The component sending the message, either 0 or 1
 int type = MAV_TYPE_QUADROTOR; ///< This system is an quadrotor

uint8_t autopilot_type = MAV_AUTOPILOT_PX4; //< PX4 firmware
 uint8_t system_mode = MAV_MODE_MANUAL_ARMED; ///< Booting up
 uint32_t custom_mode = 0; ///< Custom mode, 0 since not using this
 uint8_t system_state = MAV_STATE_STANDBY; ///< System ready for flight
 // Initialize the required buffers
 mavlink_message_t msg;
 uint8_t buf[MAVLINK_MAX_PACKET_LEN];

// Pack the message
 mavlink_msg_heartbeat_pack(sysid,compid, &msgg, type, autopilot_type, system_mode, custom_mode, system_state);

// Copy the message to the send buffer
 uint16_t len = mavlink_msg_to_send_buffer(buf, &msg);
 pxSerial.write(buf,len); // Write the message through the serial port I sent
}
void set_Position(mavlink_message_t &msg, float velx)
{
 mavlink_set_position_target_local_ned_t sp;

sp.type_mask= 0b110111110111; // Only velocity_x is set for testing.
 sp.coordinate_frame = MAV_FRAME_LOCAL_NED;
 sp.vx =velx ; // unit: m/s 
 sp.target_system = target_system_id; // Target_sysid = 1 since I am sending command to pixhawk
 sp.target_component = target_component_id;// Target_compid = 0 or 1, but I use 1.
 mavlink_msg_set_position_target_local_ned_encode(companion_id,component_id,&msg,&sp);
 send_Message(msg); // passs the msg to send_Message in order to write message to pixhawk via serial port
 Serial.print("Velocity x: ");
 Serial.println(sp.vx);

}

**Comment by LorenzMeier** [comment]
I'm afraid, but we can't assist with user-implementations in the MAVLink issue tracker. Please turn to http://discuss.px4.io if you want to ask questions. Make sure that you take the time to upload your code properly formatted, as you should not force people wanting to help to try to read code without any syntax highlighting or indentation.
