### ISSUE TITLE
[Documentation] of SYS_STATUS

### ISSUE THREAD

**Issue by tuloski** [mavlink/mavlink#1117]
In [SYS_STATUS](https://mavlink.io/en/messages/common.html#SYS_STATUS) the field `onboard_control_sensors_health` says that 0 means disabled and 1 enabled, but probably it should be 0 --> healthy, 1-->broken (or vice versa). It's a copy paste error IMO.

And `current_battery` units is mA not cA.

**Comment by hamishwillee** [comment]
I've fixed the onboard_control_sensors_health as you suggested - thanks.

> And current_battery units is mA not cA.

Really? PX4 assumes it is cA: https://github.com/PX4/Firmware/blob/master/src/modules/mavlink/mavlink_messages.cpp#L592
What am I missing?

**Comment by tuloski** [comment]
Oh ok...cA? weird unit :)
