### ISSUE TITLE
Feature request: Mission changed broadcast

### ISSUE THREAD

**Issue by julianoes** [mavlink/mavlink#1134]
It would be nice if there was some kind of "mission changed broadcast" in order to tell all ground stations, SDKs etc. when a mission (or geofence) has changed and needs to be re-downloaded.

The message should support all mission types, so mission, geofence, and safe points.

FYI: @7200rpm @sanderux @JonasVautherin

**Comment by hamishwillee** [comment]
Yes - similar to  MISSION_ITEM_REACHED and MISSION_CURRENT (and I guess to how PARAM_VALUE is emitted as a broadcast whenever a param is changed).

**Comment by julianoes** [comment]
I made a suggestion: #1136.
