### ISSUE TITLE
Pl clarify behavior on received PARAM_VALUE/PARAM_EXT_VALUE/PARAM_EXT_ACK messages

### ISSUE THREAD

**Issue by olliw42** [mavlink/mavlink#1181]
**Issue:**

The parameter protocol docu says

* "PARAM_VALUE should be broadcasted"
* "The Drone will emit a PARAM_VALUE whenever a parameter is written/changed."

and the docu for PARAM_SET says

* "PARAM_SET ... IMPORTANT: The receiving component should acknowledge the new parameter value by sending a PARAM_VALUE message to all communication partners. This will also ensure that multiple GCS all have an up-to-date list of all parameters."

By logical extension one would thus conclude that the intended behavior here is that a component which keeps an internal list of the parameters of ANOTHER component keeps its internal list updated without polling, which implies that said component **MUST** digest and handle received PARAM_VALUE messages, even if it was not triggered by itself !!!

A similar conclusion one would draw for the PARAM_EXT message set, and I thus refer only to PARAM_VALUE, with the explicit understanding that anything said extends to the PARAM_EXT messages.

Unfortunately, this implied requirement, or required behavior, of e.g. a GCS, is not clearly stated anywhere.

**Testing:**

I've tested two main ground control stations, QGC and MP, in that regard, with result

* MP appears to NOT update it's parameter list when it receives an unexpected PARAM_VALUE from a component. It appears to only digest those which it receives as reaction to it's own triggers.

* QGC in contrast appears to DO update it's parameter list when it receives unexpected PARAM_VALUE or PARAM_EXT_ACK messages. This is so both for the parameter screen as well as for the CameraManager GUI screen.

**Proposal:**

As a component developer it is most crucial to know if one can rely on the implied behavior or not. I also think (hope) it's needless to say that various practical and very realistic situations exist where the implied behavior would be crucial.  I thus would suggest to change the docs such as to make this clear and part of the specified behavior.

QGC appears to doing it already correctly, and there is thus no risk to break it by doing so.

MP appears to not do it, but the proposed addition would not break anything in any way, it only would move MP from "maybe/maybe not compliant" to "not compliant".

So, I would strongly suggest adding such clarification.

Cheers, Olli

**Comment by julianoes** [comment]
I think that makes sense.

**Comment by olliw42** [comment]
I maybe should add - in case it isn't present - that the concept bears a significant vulnerability in that a PARAM_VALUE/PARAM_EXT_SET may be lost on a channel, and the recipient's internal parameter list go out of sync. The emitting component has no way to check if all recipients have received it and could update their internal parameter list. The implication is sour, namely that no GCS can rely on the correctness of it's internal parameter list, except when it's the only one writing to a component and always polls. That's a vulnerability which had been there "since always", and I couldn't think of a resolution of it. The relevant point here: This could be seen as a valid argument AGAINST the above behavior.

**Comment by edwinhayes** [comment]
I think from memory that QGC/PX4 polls a hash of the parameter set, which can be used to validate the internal list?  Not APM though.  Also, APM has parameters which can enter/leave scope dynamically, based on values of other parameters; the specification doesn't cover what should happen (regarding sending values) in this case?

**Comment by hamishwillee** [comment]
I can canonically state that the intention of the API is as @olliw42 suggests - PARAM_VALUE gets broadcast whenever the param gets set, and everything on the link that cares about the parameters are supposed to update their internal lists. 

This works fine for the original sender, which is expected to resend the request if it doesn't get the PARAM_VALUE response. 

As noted is flawed for the general case because it is possible to miss changes and have an invalid list. PX4 has a hash, but it is explicitly not in the set: https://mavlink.io/en/services/parameter.html#px4

I had a chat about this with @tridge 8 months or so ago and his take was that for various reasons on ArduPilot a hash would not work reliably (I think to do with param set being able to change dynamically as a side-process). He is supposed to be working on a new version of the service that is capable of downloading the whole param set in under a second or 2; which would make it practical to redownload every time you want to know the set canonically. 

I do not know what we should do given that this is not 100% reliable. Perhaps clarify the intent -  [after](https://mavlink.io/en/services/parameter.html#write) "This is a broadcast message (sent to all systems)." to say:

> **Note** GCS (and other systems) that are interested in the parameters should update their internal parameter list when PARAM_VALUE is received. This approach is robust for the original sender, which can resend the request if no PARAM_VALUE is received. Note however that it is not 100% reliable for other systems on the link that may miss messages. No particular solution to this problem is recommended in this version of the protocol.

**Comment by olliw42** [comment]
great to hear that you essentially seem to agree.

the hash thing I think has little if nothing to do with the issue at hand here, it's merely a means to decide if a paramlist needs to be reloaded (in total), but can't say which of the params need to be reloaded
also ArduPilot's folded/dynamic parameters is an issue for it's own, IMHO.

I guess I would move such a note box to a bit more prominent location, e.g. to the end before the last blue box (on MAV_CMD_DO_SET_PARAMETER)

I wouldn't be totally happy with the last sentence "No particular solution to this problem is recommended in this version of the protocol". The text reads to me as if a GCS isn't really really supposed to update also for "unexpected" PARAM_VALUE but that what to do is left to each GCS own decision. I also would think that one could give a recommendation. For instance, in my implementation I'm an sending the "unexpected" PARAM_VALUE three times. Not 100% reliable, but works sufficiently well in practice (and I have seen that such a doubling/tripling is used for other "important" messages too in some implementations). Maybe there is a better recommendation.

I guess I would strengthen the first sentence to "Note GCS (and other components) that are interested in the parameters should (must) update their internal parameter list whenever a PARAM_VALUE is received, if initiated by itself or other components." 

BTW, I guess it should better say "and other components" instead of "and other systems", also e.g. in the docs in point 3. it should say  "3. ... This is a broadcast message (sent to all components)."

**Comment by julianoes** [comment]
I think the behaviour where you emit the PARAM_VALUE for anyone listening makes sense.
Therefore, I think, we should do (and document) the same for `PARAM_EXT_VALUE` (if we haven't already).

Also, I would argue that it would be nice if MP did that too and I would suggest that you @olliw42 create a feature request to MP to support it.

**Comment by hamishwillee** [comment]
@olliw42 @julianoes Please see fix for docs in https://github.com/mavlink/mavlink-devguide/pull/204. This is slightly different than proposed - most of the information is in limitations section - which I link up to from the actual section where the problem occurs.

Please check.

**Comment by hamishwillee** [comment]
@dogmaphobic - For parameter protocol, PARAM_SET causes PARAM_VALUE to be broadcast, allowing multiple GCS/recipients to maintain synch with parameters despite changes from other components (providing messages are not dropped). 

Is this behaviour also expected for PARAM_EXT_VALUE? Can it be? Does it have a better way for multiple systems to keep in sync?

**Comment by olliw42** [comment]
I think the "difference" is that in the case of the EXT param service a GCS must track both `PARAM_EXT_VALUE` and `PARAM_EXT_ACK`, since these both are broadcasting latest param values.

in the case of the normal param service all requests (LIST,READ,SET) result in a `PARAM_VALUE` response

in the case of the EXT param service the LIST,READ requests result in a `PARAM_EXT_VALUE` response, and the SET request in a `PARAM_EXT_ACK` response.

note that the last isn't yet well documented, which is the aim of #1140 and #1143

**Comment by olliw42** [comment]
I think your statement _"In theory, they both (regular and EXT) work in the same way."_  was correct, since it was in the context of whether  everything on the link interested in a parameters should update their internal lists. In that regard `PARAM_VALUE`, `PARAM_EXT_VALUE` and `PARAM_EXT_ACK` should all be handled the same.

the differences you describe are certainly very relevant, but probably in the context of #1143

**Comment by olliw42** [comment]
I think we both say exactly the same :)

I also think that hamishwillee's question in https://github.com/mavlink/mavlink/issues/1181#issuecomment-525093915 is fully answered, that is, that like `PARAM_VALUE` also `PARAM_EXT_VALUE` and `PARAM_EXT_ACK` are broadcasted, and allow multiple GCS/recipients to maintain synch with parameters (if not dropped). The docu should be similarly adapted for them.

**Comment by olliw42** [comment]
@hamishwillee 

I'm sorry, but this needs to be reopened, or a new issue be created:

The changes in the mavlink-devguide ONLY concern the PARAM message set, but **NOT** also the `PARAM_EXT` message set, for which the docs also needs to be modified to reflect the intended behavior !!!

If you wish me to create a new issue for that, pl tell.

**Comment by hamishwillee** [comment]
> Here is a random example from the PHP documentation for example: https://www.php.net/manual/en/function.session-start.php Look at the bottom of the page. It would be better when it's curated but you get the idea.

@dogmaphobic FWIW I love those systems as a user but they are a pain in the neck if you're a maintainer. 
The best commenting is inline, and for that usually you need a system that is designed for it, which in turn means something dynamic, hosting services, patches etc. 
We could use something like https://disqus.com/ to retrofit commenting at the end of current pages, but you still need someone to look at every single page and make sure that spam gets removed etc etc. 

Upshot, yes, but I don't think this community has the resource to maintain that.

**Comment by hamishwillee** [comment]
@olliw42 Further discussion can happen in https://github.com/mavlink/mavlink-devguide/pull/210

**Comment by olliw42** [comment]
THX

**Comment by olliw42** [comment]
> Also, I would argue that it would be nice if MP did that too and I would suggest that you @olliw42 create a feature request to MP to support it.

for your info, I've placed a corresponding issue:
Correct behavior on received PARAM_VALUE/PARAM_EXT_VALUE/PARAM_EXT_ACK messages https://github.com/ArduPilot/MissionPlanner/issues/2221#issue-495109687
so MP is informed and it's all in their hands now
