### ISSUE TITLE
Documentation rendering mixes messages with commands visually, confusing developers

### ISSUE THREAD

**Issue by LorenzMeier** [mavlink/mavlink#1191]
@hamishwillee Commands need a different visual style because developers do not understand that a command is not a message. They need to render into a different format.

**Comment by hamishwillee** [comment]
@LorenzMeier Obvious "solution" is to add a visual identifier to every type indicating what it is - command, message, enum. This could be a prefix or suffix, and it could link to the section heading, which then explains what the contained types are. If we do this then the first one would be my preference.

![image](https://user-images.githubusercontent.com/5368500/62338133-b7446200-b51a-11e9-842a-b31feec38197.png)

Reasons not to do it are that lots of work has gone into making these as compact as possible to reduce download/load time. Adding links and new text counters that. Also, they are already pretty different, and you might argue that someone who is confused by this now will remain confused by whatever we do ... see the difference now:

![image](https://user-images.githubusercontent.com/5368500/62337738-3a64b880-b519-11e9-8602-9e0844b8392b.png)

**Comment by hamishwillee** [comment]
Another alternative might simply be to change the font on everything in these sections. Probably less effective.

**Comment by hamishwillee** [comment]
I tried this an it buggers up the menu. Might work with an icon, but not sure anything would meaningfully tell the difference between a command and message visually.

![image](https://user-images.githubusercontent.com/5368500/62340918-97b23700-b524-11e9-978a-c588d5fef49a.png)

**Comment by hamishwillee** [comment]
OK, so proposal below. Basically same thing, but link/text for the type is in the description. Does this work for you?

![image](https://user-images.githubusercontent.com/5368500/62340957-c29c8b00-b524-11e9-89f5-afafcb20aca6.png)
