### ISSUE TITLE
Is MISSION_ITEM_REACHED supported in the guided mode? If not, why is that so?

### ISSUE THREAD

**Issue by sona-19** [mavlink/mavlink#1203]

**Comment by julianoes** [comment]
I believe this question is referring to ArduPilot, correct? This repository is about the MAVLink protocol and not about what is implemented by a autopilot software like PX4 or ArduPilot.

(If you add some more description or context we might be better able to answer the question.)

**Comment by sona-19** [comment]
Okay. I got it
