### ISSUE TITLE
CSharp example classes

### ISSUE THREAD

**Issue by MooonWalker** [mavlink/mavlink#122]
Hi, 

i am just trying to implement the mavlink to C# project for Netduino Plus 2.
In the generated Mavlink.cs i saw reference to Mavlinksettings class.
Where i can find this class and all the other used classes to a working example project?

Many thanks for help.

**Comment by amilcarlucas** [comment]
This is not an issue, it is a support question. Please post support questions on the support forum.

AFAIK this can be closed now.

**Comment by MooonWalker** [comment]
For me it was an issue.

**Comment by hamishwillee** [comment]
@MooonWalker What Amilcar is saying is that this system is for bug posts, and your issue is a support request. The right place for support requests is the forum/discussion channels: https://mavlink.io/en/#support
