### ISSUE TITLE
Pl add discussion about COMPONENT_INFORMATION to dev call agenda, if possible

### ISSUE THREAD

**Issue by olliw42** [mavlink/mavlink#1280]
In the next dev call, this Wed, I would like - if possible - discuss a bit more thoroughly how one could progress with COMPONENT_INFORMATION.

The COMPONENT_INFORMATION message has been merged to mavlink as WIP, but - at least as much as I can see - it's currently totally unclear what the best ways would be to bring it to fruition.

Notes:

As regards putting topics on the dev call agenda, the wiki says "_Add topics that you'd like to discuss and issues you'd like to unblock._" but I couldn't find any further explanation of how one would do that. So, I miss-use this issue here, sorry for that.

I'm actually not sure the topic belongs into the mavlink dev call, in light of rroche's recent "Meet the Volunteers" thread one could think that the "Community Management" level would be more appropriate but I couldn't find more about it, hence I'm here. Also sorry for this. 

Putting up this issue was the best effort I could see. :)

**Comment by hamishwillee** [comment]
Works for me. I added the label and will add to agenda.

**Comment by olliw42** [comment]
thanks so much. Very cool.

just to avoid any mistakes on my side: 

The meeting starts at 9:00 AM CET = 9:00 AM MET = 9:00 Zürich time = 9:00 Berlin time, right?

(
I ask since here https://mavlink.io/en/about/support.html it says 9:00 AM CET: 

![mav-w](https://user-images.githubusercontent.com/6089567/70504513-3596bd80-1b26-11ea-941c-c090fe42d888.jpg)

but in https://www.dronecode.org/calendar/ 

![mav-dc](https://user-images.githubusercontent.com/6089567/70504519-37f91780-1b26-11ea-8fb8-2c5a5a0290b2.jpg)

it shows it at 8:00 - 9:00, and explicitely says "The calendar below shows events for the Zurich timezone." at the top and "Terminanzeige in der Zeitzone: Mitteleuropäische Zeit - Zürich" at the bottom, so not UTC but 8:00 AM MET = 8:00 AM CET since CET = MET 

!?!?!?!?
)

**Comment by hamishwillee** [comment]
6pm tomorrow for me in Melbourne. I.e. tomorrow but an hour before now. Looking at GMT it is now 8am, so 7am GMT tomorrow.

I have nothing to do with that calendar. @mrpollo :-)

**Comment by olliw42** [comment]
LOL ... so I have to do some math ...

GMT is UTC, and MET = CET = UTC+1.

so 7:00 AM GMT would mean 8:00 AM MET/CET/Zürich/Berlin time !?!?!?!

so, the drone code calender would be right, and the mavlink-doc https://mavlink.io/en/about/support.html entry would be off by 1 hour ??

would you mind double checking if the mavlink-doc entry is correct/wrong?

**Comment by julianoes** [comment]
It starts at 8am during winter and 9am in summer :smile:. So tomorrow 8:00.

**Comment by olliw42** [comment]
many thx, sir.

I'm glad I asked

The byproduct is that the info in the mavlink docs isn't correct, since it's currently winter and we have MET = UTC+1 = GMT+1 = CET, and it currently should thus say 8:00 AM CET.

See you tomorrow.

**Comment by olliw42** [comment]
THANKS a lot for the very helpful and open discussion today. Much appreciated.

:)

(and close)
