### ISSUE TITLE
mavlink.io website not accessible 

### ISSUE THREAD

**Issue by mtbsteve** [mavlink/mavlink#1287]
Seems like the https://mavlink.io/en/ site is down. Thanks for fixing.

**Comment by mhkabir** [comment]
Works for me

**Comment by mtbsteve** [comment]
Its certainly not working. Tried it from different internet access points.
[https://1drv.ms/u/s!AnKeW8KMoCcyw0tQgy2ajwtcjVPA?e=Fmfahu](url)

**Comment by LorenzMeier** [comment]
Works also from here. I'm closing this for now assuming it is a local issue.

**Comment by LorenzMeier** [comment]
Thank you for taking the time to report it!

**Comment by vooon** [comment]
Works for me too.

**Comment by mtbsteve** [comment]
@LorenzMeier It is not accessible from my environment:
- iPhone - Chrome and Safari no access by LTE/German Telekom nor via wifi
- PC - Chrome, Internet explorer neither via wifi nor LAN
- Android Tablet -Chrome neither LTE nor wifi
PS: I live in Germany... and the rest of the internet works well...

**Comment by hamishwillee** [comment]
Works from Australia.
This is hosted on github pages, so should work anywhere github works.

**Comment by mtbsteve** [comment]
ok I am probably the only person on earth who cannot access the mavlink.io website. 
Anyway at least I can access https://github.com/mavlink/mavlink-devguide
and read the documentation from there so I am good for now.  
Still it would be nice if someone could find out what makes this site behavior  different from the rest of the internet.

**Comment by hamishwillee** [comment]
I hope so :-). FMI can you see http://docs.px4.io/master/en/index.html ?

**Comment by mtbsteve** [comment]
Yes I can confirm that http://docs.px4.io/master/en/index.html
works perfectly well for me.

**Comment by hamishwillee** [comment]
That's odd. They live on the same infrastructure. I don't know how to help debug this for you.

**Comment by devurandom** [comment]
#1289 is a duplicate.

Reason for this is that GitBook changed their product and DNS scheme:

> In short, CNAME to hosting.gitbook.com.
>
> If you are a v1 user, you may have been used to using www.gitbooks.io , which only works for legacy.gitbook.com and will not work for new users.
>
> Note: GitBook legacy will soon be deprecated. Contact us to help you migrate your content.

**Comment by mtbsteve** [comment]
Thanks for the clarification @devurandom !
@LorenzMeier @hamishwillee would be great if you could migrate the mavlink.io content accordingly.

**Comment by hamishwillee** [comment]
@dagar ^^^^
