### ISSUE TITLE
Packet Loss Calculation

### ISSUE THREAD

**Issue by 0xF0F0F0F0** [mavlink/mavlink#1315]
Hi,

I wanted to know if there is an accurate way to calculate packet loss on a mavlink channel. I have come across calculation using message sequence number but i have a few questions:
1. What is the difference between seq number in mavlink packet vs. current_rx_seq in mavlink_status?
2. If i lose more than 255 sequence numbers, will it affect my calculation? (since seq num is 0-255)

**Comment by hamishwillee** [comment]
1. I'm guessing that the current_rx_seq is filled every time you get a new packet, from the packet seq. If the message you expect is not received then you'd know one was dropped. You'd have to look at the code though. 
2. Depends on your calculation :-). But if you're using this for packet loss, then yes, it will wrap over. So you need to account for that. 

You'll have to expand on what you're doing for us to comment on how good the algorithm is. There are many ways this might be done.

Closing. Assumption is that poster has lost interest.
