### ISSUE TITLE
Message to substitute GNSS data in FC

### ISSUE THREAD

**Issue by wucke13** [mavlink/mavlink#1320]
Hi,
is there a message which allows one to overwrite the GNSS data (global current position of the vehicle) in the FC? If not, are there any plans to implement one?

**Comment by amilcarlucas** [comment]
Try the HIL message or the GPS_INPUT message

**Comment by hamishwillee** [comment]
Thanks @amilcarlucas. Sorry @wucke13  - I completely missed this message. 

Note that 
- [GPS_INPUT](https://mavlink.io/en/messages/common.html#GPS_INPUT) might not be implemented on your flight stack. If it is, it may be fused with other information - i.e. it should be fused with other sources, not replace them. 
- The HIL messages are only used for hardware simulation - it is unlikely they will work in a normal airframe.

So perhaps best to further explain why you need this message/use case?

**Comment by wucke13** [comment]
Hi, thanks for the responses. I'm working on a MAVLink to MSP bridge which allows one to use a drone which supports MSP (namely iNAV based ones) in a MAVLink network. However, one of the remaining challenges is GPS and Waypoint navigation. AFAIK MSP only understands a global position. I would prefer the bridge to have only two communication ends, one for MAVLink and one for MSP. So, in order to push substituted location information to the FC (e.g. from a POZYX system), it would be necessary to push global position data to the Drone (as MSP doesn't understand local position frames), and in order to push a global position to the bridge there needs to be a MAVLink message for it. I hope this clears up my intentions a bit. 

Also, I think it is a nice thing to be able to substitute global position because it allows one to use MAVLink on the component level to transparently use a high quality position device without having it emit NMEA or similar things.

**Comment by amilcarlucas** [comment]
AFAIK GPS_INPUT is the messag you need.

**Comment by wucke13** [comment]
@amilcarlucas Ah, thank you!
