### ISSUE TITLE
MAVLink Version 0.9 error

### ISSUE THREAD

**Issue by ed-muthiah** [mavlink/mavlink#1328]
Hi folks, 

According to this error I apparently have MAVLink 0.9 installed on my Navio2. How can I update this to MAVLink 1.0 or 2.0 in the linux terminal? I'm using ROS Kinetic LTS.

> Critical message: "MAVLink Version or Baud Rate Mismatch" "Your MAVLink device seems to use the deprecated version 0.9, while APM Planner only supports version 1.0+. Please upgrade the MAVLink version of your autopilot. If your autopilot is using version 1.0, check if the baud rates of APM Planner and your autopilot are the same."

Thanks!

**Comment by hamishwillee** [comment]
Depends on how you installed it in the first place (?)

Given you're working with ArduPilot, suggest you try follow up in the ArduPilot specific forums for MAVLink https://discuss.ardupilot.org/c/ground-control-software/mavlink/116 or ROS.

Alternatively,
