### ISSUE TITLE
Reserve Component ID 68 for RADIO

### ISSUE THREAD

**Issue by olliw42** [mavlink/mavlink#1345]
The SiK radios, which are still in wide-spread use, for historical reasons send out RADIO_STATUS messages with source id 51 and component ID 68.

Component ID 68 is however marked in the spec as MAV_COMP_ID_USER44, i.e. as an id freely chosable by a user.

I suggest to remove MAV_COMP_ID_USER44, and replace it with MAV_COMP_ID_RADIO, in order to put things on a proper formal basis (and avoid pitfalls even if admittedly unlikely)

Thanks
Olli

**Comment by hamishwillee** [comment]
I think this makes sense.

**Comment by julianoes** [comment]
Make sense to me.

**Comment by olliw42** [comment]
for your convenience: https://github.com/mavlink/mavlink/pull/1405

:)

**Comment by olliw42** [comment]
done. THX!
hence closing
