### ISSUE TITLE
MAV_CMD_DO_MOUNT_CONFIGURE not deprectaed

### ISSUE THREAD

**Issue by olliw42** [mavlink/mavlink#1384]
MAV_CMD_DO_MOUNT_CONTROL and  MAV_CMD_DO_MOUNT_CONTROL_QUAT are marked as deprecated, as they should, but MAV_CMD_DO_MOUNT_CONFIGURE  is not. Is this on purpose? Should be an oversight, right?

**Comment by julianoes** [comment]
This sounds like an oversight, thanks! Could you make a PR to fix it?
