### ISSUE TITLE
custom msg

### ISSUE THREAD

**Issue by Ador2** [mavlink/mavlink#1391]
how can i make a new message to send and get received by ardupilot, and be sent and received by QGC???
i have added my custom message in ardupilotmega.xml and generated the headers for ardupilot to read, i have added the same headers to QGC, but the message never makes it to QGC, can someone tell me what the process as in dummy terms -_-

**Comment by hamishwillee** [comment]
Best place to start would be https://ardupilot.org/dev/docs/code-overview-adding-a-new-mavlink-message.html, and then search for similar questions like: https://discuss.ardupilot.org/t/how-to-create-your-own-custom-messages-in-mavlink/26818

The integration of custom messages is really very autopilot/GCS dependent so not something we can advise on here. So I'm going to close this, and I advise that if you have further questions use the ardupilot forums.
