### ISSUE TITLE
VIDEO_STREAM_INFORMATION marked as WiP.

### ISSUE THREAD

**Issue by ben-crowhurst** [mavlink/mavlink#1448]
Hey, I was looking to implement VIDEO_STREAM_INFORMATION as a way of getting available video feeds.  I can see QGroundControl contains an implementation [here](https://github.com/mavlink/qgroundcontrol/blob/2e033034dc3944d329bb9fc3a52018d34d527d8e/src/Camera/QGCCameraControl.h#L26).  However, it is marked as WiP and has been for quite some time. 

Will this message ever get ratified and make it into the mainstream protocol?

**Comment by hamishwillee** [comment]
@dogmaphobic [VIDEO_STREAM_INFORMATION](https://mavlink.io/en/messages/common.html#VIDEO_STREAM_INFORMATION) is now in production systems, so any reason not to remove the WIP?

Ditto for the others? I can do the work if you confirm this is food to go.

**Comment by hamishwillee** [comment]
@ben-crowhurst Sorry for delay. There was no response from gus, but I've created PR to remove the WIP now: https://github.com/mavlink/mavlink/pull/1513

You can treat this as "good to go".
