### ISSUE TITLE
MAVLink docs: incomplete for common

### ISSUE THREAD

**Issue by olliw42** [mavlink/mavlink#1464]
minimal.xml is now included in common.xml, but the respective messages, enums and so on are NOT also listed on the documents page
e.g, an important message like HEARTBEAT is now not listed anymore :)

**Comment by hamishwillee** [comment]
https://mavlink.io/en/messages/minimal.html#HEARTBEAT

Common includes minimal.xml and this is listed. Are you suggesting that the dialect files should be auto-expanded out? I'm somewhat tempted by the idea.

**Comment by olliw42** [comment]
> Are you suggesting that the dialect files should be auto-expanded out?

yes

I use the docs very often, and find it very unfortunate and less practical as it is right now.

**Comment by hamishwillee** [comment]
Fair enough. I'll have a look at the docs generator in the next week or so. I think I can do a relatively easy hack.

**Comment by olliw42** [comment]
great!

I realize I might have been a bit unclear. I guess I'm not actually suggesting to generally expand out the included xmls, i.e., also for dialects (dialects in the sense of the one google doc ). I suggest so only for standard and common (and other similar, if there ever are other similar). For dialects I guess I would handle it as you currently do it, i.e., just show the additions by that dialect.

**Comment by hamishwillee** [comment]
@olliw42 Thanks. I misinterpreted you, but it doesn't matter because the dev call came to the same conclusion :-). I created a fix but waiting on review of the "approach".

**Comment by olliw42** [comment]
this seems to have addressed to some reasonable extend, so I close.
