### ISSUE TITLE
Common.xml Docs: Cmds out of order

### ISSUE THREAD

**Issue by olliw42** [mavlink/mavlink#1495]
the screen shot says it.  520 < 519 < 521 :D:D:D

![cmdbug](https://user-images.githubusercontent.com/6089567/94395004-f1c97f00-015e-11eb-926d-17edae51bb93.jpg)

**Comment by hamishwillee** [comment]
Thanks @olliw42 . I did not see that when I reviewed the PR that pulled it back into common.
