### ISSUE TITLE
error with pip package pymavlink

### ISSUE THREAD

**Issue by bhack** [mavlink/mavlink#150]
Generated python file from mavgen_python.py need to have:

from pymavlink.generator.mavcrc import x25crc

instead of:
from ...generator.mavcrc import x25crc

Because actually we got this on pip installed pymavlink:
    from ...generator.mavcrc import x25crc
ValueError: Attempted relative import beyond toplevel package

**Comment by wiseman** [comment]
This still happens with a freshly pip installed pymavlink.  Is there some reason this issue was closed?

**Comment by AlexisTM** [comment]
Dear, 

I found one solution.

As seen [here](http://docs.ros.org/jade/api/mavlink/html/classpymavlink_1_1mavutil_1_1x25crc.html), x25crc is `mavutil` now.

You can just change (mavlink.py generated) : 

```
from ...generator.mavcrc import x25crc
```

to

```
from pymavlink.mavutil import x25crc
```
