### ISSUE TITLE
I am missing .h and .cpp in the library

### ISSUE THREAD

**Issue by BaSX8** [mavlink/mavlink#1522]
I unzipped the library into the arduino library folder. But the mavlink folder neither contains the .h nor the .cpp file. Arduino IDE detects the library but I get the error, that .h is missing. Am I missing something? 

Error:
Invalid library found in C:\Users\basti\OneDrive\Dokumente\Arduino\libraries\mavlink: no headers files (.h) found in C:\Users\basti\OneDrive\Dokumente\Arduino\libraries\mavlink

**Comment by amilcarlucas** [comment]
You need to generate the files using pymavlink. Follow the documentation on mavlink.io and you should be fine
