### ISSUE TITLE
Documentation fix: #124 GPS2_RAW, dilution unit wrongly listed as cm

### ISSUE THREAD

**Issue by rotorman** [mavlink/mavlink#1572]
Please check the documentation of [GPS2_RAW (#124)](https://mavlink.io/en/messages/common.html#GPS2_RAW) at: [https://mavlink.io/en/messages/common.html#GPS2_RAW](https://mavlink.io/en/messages/common.html#GPS2_RAW)

It incorrectly lists _cm_ as dilution units for HDOP, VDOP (fields eph, epv). Dilution is unitless.
(On the other hand, first GPS message, [GPS_RAW_INT (#24)](https://mavlink.io/en/messages/common.html#GPS_RAW_INT), has correctly no unit listed).

**Comment by hamishwillee** [comment]
So does [HIL_GPS](https://mavlink.io/en/messages/common.html#HIL_GPS).

I think you're right - @julianoes can you confirm?

**Comment by julianoes** [comment]
I think @rotorman is right.

**Comment by hamishwillee** [comment]
Thanks @rotorman. I have submitted PR for this in #1580
