### ISSUE TITLE
Keep Receiving RE-request WPS 1234

### ISSUE THREAD

**Issue by jiapau** [mavlink/mavlink#1576]
After sending mission thru mavproxy, it kept sending Re-Requesting WPS [ 0, 1, 2, 3, 4]

**Comment by hamishwillee** [comment]
This sounds like something you should initially debug through discussions with MAVProxy: https://discuss.ardupilot.org/c/ground-control-software/mavproxy/73

 If it proves to be a MAVLink problem you can reopen.
