### ISSUE TITLE
MAVLink 2.0 ideas

### ISSUE THREAD

**Issue by DrTon** [mavlink/mavlink#166]
I have some ideas how to make MAVLink messages more consistent and functional, but it will break compatibility with current version, so let's call it MAVLink 2.0 :)
- Use common format for angles everywhere. Now there are a lot of different formats for angles: deg [-180...180],, deg [0...360], deg \* 0.01 [0...360], rad [-pi...pi], rad[0...2_pi] etc. It's extremly confusing, was source of many bugs. I suggest to use single format for all angles that will have enough precision for everything we need: ''uint16_t'', ''0 -> 0 rad'', ''MAX_UINT16 + 1 -> 2_PI rad''. It can be interpreted as ''int16_t'', only band will change from ''0...2*PI'' to ''-PI...PI''. It maybe not so human readable as float, but for programmer I think it will be more clear - to use single format everywhere.
- Use quaternions instead of euler angles. I think every application / device that uses mavlink can calculate everything it need from quaternion.
- Add global time to GLOBAL_POSITION_INT: we live in 4D space and 3D position of object without knowledge of time means nothing. On other side, if we know time and also velocity, we can extrapolate position very precise. Assumption that link is fast and we received position when it was generated is simply wrong, as shown my expirience with follow, latency can reach 2-3 seconds sometimes, for 60km/h speed it's 30m - too much for UAV.
- Remove redundant fields: e.g. GLOBAL_POSITION_INT has fields ''alt'' and ''relative_alt''. But it's global, not local position, and relative altitude (above ground) means nothing because ground level may vary significantly. If user needs altitude above home he can calculate it from altitude AMSL and home position alt. It also has ''hdg'' that is the same as yaw in attitude message, why it should be here?
- Remove all exotic messages from ''common'' part. E.g. it's very strange to see in ''common'' messages SET_QUAD_SWARM_LED_ROLL_PITCH_YAW_THRUST. Looks like everybody use 4 (but not more!) quads (not hexa or octo!) to bring some LEDs to sky. In the same time SET_GLOBAL_POSITION_SETPOINT_INT has no any ''destination_ID'' field, so can't be used for more than one vehicle.

We need to rewrite messages definitions from scratch, adding messages one by one only after full review, keeping in mind expirience, but forgetting about current implementation. Protocol should be designed so user will never think which message he should use to get or send some info. We should leave only one clear way.

**Comment by amilcarlucas** [comment]
@LorenzMeier he makes some good points here. How about using this one as the first official RFC ?

**Comment by LorenzMeier** [comment]
Could you send a PR? I will close this meanwhile.
