### ISSUE TITLE
Got COMMAND_ACK: NAV_LOITER_TURNS: UNSUPPORTED

### ISSUE THREAD

**Issue by YusufMuharremDaskaya** [mavlink/mavlink#1664]
I am trying to use NAV_LOITER_TURNS with this paramaters (1, 0, 0, 0, 0, 0, 0) returns Got COMMAND_ACK: NAV_LOITER_TURNS: UNSUPPORTED. What can be the problem? Note: I am trying to use this command in guided mode.

**Comment by hamishwillee** [comment]
Exactly what it says in [MAV_RESULT_UNSUPPORTED](https://mavlink.io/en/messages/common.html#MAV_RESULT_UNSUPPORTED) - Command is not supported (unknown).

So the command is not supported on your flight stack in the current flight mode (guided mode). It might be supported on the same flight stack in missions.

This MAV_CMD isn't really intended for commands - it is expected to be used in missions. There is another command that is "more designed" for guided mode [MAV_CMD_DO_ORBIT](https://mavlink.io/en/messages/common.html#MAV_CMD_DO_ORBIT), but while this does support turn based specification, that has not yet been implemented (if you tried to specified the turns on PX4 you'd get an error MAV_RESULT_DENIED - supported command but invalid parameters).

What flight stack are you working on?
