### ISSUE TITLE
mavkml.py not working correctly?

### ISSUE THREAD

**Issue by mikemccauley** [mavlink/mavlink#167]
Hi, seems the latest version of mavkml.py is not working with tlog files from MissionPlanner or MAVProxy sent by APM2.6 (at least). The resulting KML file has no position data points in it.
The input tlog files have many GPS_RAW_INT mavlink data items containing 'lat', 'long', 'alt' items. the lat and long are in 1x10^^7 degrees and the alt is in 1x10^^3 meters.
But it appears that mavkml.py is looking for data points called 'Lat', 'Lon' and 'Alt' (note the case) and that the data be in degrees and meters. So mavkml.py does not select the data and even if it did the data is not ranged correctly.

**Comment by LorenzMeier** [comment]
Closing as stale.
