### ISSUE TITLE
Body frame

### ISSUE THREAD

**Issue by Larsonto** [mavlink/mavlink#1683]
I am using mavros_msgs/PositionTarget message (http://docs.ros.org/en/api/mavros_msgs/html/msg/PositionTarget.html)

Currently the drone is in world frame. But I want to use my drone in body frame i.e as the drone moves the origin should always be the drone’s center. How to achieve this?

**Comment by hamishwillee** [comment]
From a MAVLink perspective the body frame you are talking about is [MAV_FRAME_BODY_FRD](https://mavlink.io/en/messages/common.html#MAV_FRAME_BODY_FRD) or possibly ([MAV_FRAME_BODY_NED](https://mavlink.io/en/messages/common.html#MAV_FRAME_BODY_NED)) and the position would be set using [POSITION_TARGET_LOCAL_NED](https://mavlink.io/en/messages/common.html#POSITION_TARGET_LOCAL_NED)

BUT not every flight stack supports every message or frame, and what ROS does to abstract this is something I can't comment on.

Suggest you raise this in the ROS channel.
