### ISSUE TITLE
Don't include <inttypes.h> in mavlink_helpers.h

### ISSUE THREAD

**Issue by Susurrus** [mavlink/mavlink#170]
This is unnecessary and `<stdint.h>` is the only thing that should be included. On some platforms (like the PIC 16-bit compilers) don't even have `<inttypes.h>`. This doesn't break anything for me in VS2010 or when compiling with Microchip's XC16 compiler, so I think this will work for all supported platforms.

**Comment by Susurrus** [comment]
Has anyone compiled mavlink header files on older versions of visual studio? I'm pretty certain this code is currently broken. Since MSVC2008 is the last release that doesn't support stdint.h, I'm going to suggest we trigger an `#error` when using that old of a compiler and otherwise just always import stdint.h, which is basically supported everywhere now.

**Comment by tridge** [comment]
fixed in master, thanks
