### ISSUE TITLE
Trajectory Sharing Microservice

### ISSUE THREAD

**Issue by flybrianfly** [mavlink/mavlink#1714]
I would like to explore developing a trajectory sharing microservice. At a high level, the concept is that UAS could broadcast a portion of their planned trajectories to each other. UAS could evaluate whether a conflict is expected to occur and adjust their trajectories to avoid a collision.

An initial concept of a message is:
• Point P0: a WGS84 latitude, longitude, and altitude. For straight line segments, this indicates the starting position. For circular arc segments, this indicates the center of circular arc.
• Point P1: a WGS84 latitude, longitude, and altitude. For all segment types, this indicates the end of the segment.
• Turn radius: 0 for straight line segments and the turn radius for circular arcs. The sign indicates the turn direction, positive for a right turn and negative for a left turn.
• P1 ETA: the estimated time of arrival at P1 in UTC.
• Ground speed: the estimated ground speed during the segment.
• Minimum speed: the minimum speed possible during the segment.
• Vehicle type: the vehicle type.

I'm estimating that this message could be transmitted in approximately a 44 byte frame. If transmitted at 1 Hz, the impact on radio modem bandwidth would be quite low.

If each vehicle transformed the received trajectories to it's own NED frame, a bounding box approach could be used to quickly identify whether there is a potential for a collision.

If a conflict is predicted to occur, a rapid approach to resolve the conflict is to develop right of way rules, similar to those used by manned aircraft. These could be sorted by aircraft type (more maneuverable vehicles yielding to less maneuverable vehicles) and minimum airspeed.

Is there a planned approach already in work? Otherwise, I'm planning on prototyping a protocol and simulating and flight testing to validate the approach.

**Comment by flybrianfly** [comment]
@hamishwillee, you're right, that's very similar. I had read through the [microservices](https://mavlink.io/en/services/) page and didn't see anything, but searching through [messages](https://mavlink.io/en/messages/common.html) I do see the UTM enums and message.

I think we'll work on implementing [UTM_GLOBAL_POSITION](https://mavlink.io/en/messages/common.html#UTM_GLOBAL_POSITION) then.

Thanks for pointing that out!

**Comment by hamishwillee** [comment]
You're welcome. There are more microservices to document than I have time to document. If I am ever "allowed", I will split the dialect files into separate service docs so that at least the different things you can do are better "surfaced".

**Comment by hamishwillee** [comment]
@flybrianfly If I _had_ named a microservice page **UAS Traffic Management** or **Traffic Management** would you have found this yourself? 
I'm trying to find a good title because that's key for discoverability.
