### ISSUE TITLE
mavlink_types.h:92: error: ISO C++ prohibits anonymous structs [-Werror=pedantic]

### ISSUE THREAD

**Issue by AleksandrBon** [mavlink/mavlink#1753]
On g++ compilation with "-pedantic" flag error:
mavlink_types.h:92: error: ISO C++ prohibits anonymous structs [-Werror=pedantic]
     };
     ^
mavlink_types.h:17: in definition of macro ‘MAVPACKED’
   #define MAVPACKED( __Declaration__ ) __Declaration__ __attribute__((packed))
                                        ^~~~~~~~~~~~~~~
etc.

This problem is originated in that the c++ standard forbids anonymous structs declarations
[https://stackoverflow.com/questions/2253878/why-does-c-disallow-anonymous-structs](url)

And even if mavgenerate.py one can choose to generate c++ headers, core files like mavlink_types.h stays same.

**Comment by hamishwillee** [comment]
Thanks.

@julianoes This should probably be moved to Pymavlink repo right?

**Comment by julianoes** [comment]
@hamishwillee yes it should.

**Comment by hamishwillee** [comment]
@AleksandrBon Could you please repost this in https://github.com/ArduPilot/pymavlink/issues - it is a toolchain issue, and the toolchain is managed in a separate repo.

If you don't want to track this, let me know and I can repost for you.

**Comment by AleksandrBon** [comment]
> @AleksandrBon Could you please repost this in https://github.com/ArduPilot/pymavlink/issues - it is a toolchain issue, and the toolchain is managed in a separate repo.
> 
> If you don't want to track this, let me know and I can repost for you.

done https://github.com/ArduPilot/pymavlink/issues/602

Thanks. There is also another interesting moments, i.e. when trying to compile with
-Wswitch-default it gives error that code don't have default switch-case if some files.
And what is more interesting
-Wconversion mavlink_sha256.h:217:40: error: conversion to ‘unsigned char’ from ‘uint32_t {aka unsigned int}’ may alter its value [-Werror=conversion]
That's can potentially cause overflow.

**Comment by auturgy** [comment]
Closing - has been closed in pymavlink
