### ISSUE TITLE
Manually Setting Home Position

### ISSUE THREAD

**Issue by kmelgar5** [mavlink/mavlink#1754]
This bug seems to occur randomly but after x amount of time of trying to get the home position via mavros messages, the home position never sets no matter how much time goes by. A reboot usually tends to fix and gets home position almost instantly. Is there a way to manually set home position so I don't have to reboot my vehicles every time? I tried using the mav long command, SET_HOME_POSITION ( #243 ) and MAV_CMD_DO_SET_HOME (179 ) but because a home position has not been found, one cannot override this via commands.

**Comment by hamishwillee** [comment]
MAVLink describes how the messages should work, but we don't provide the implementation for a particular flight stack or of mavros. I am therefore going to close this.

YOu should go to the discussion boards for the flight stack you are using, and then post this in the ROS or MAVROS channels in that forum.
