### ISSUE TITLE
CMake Build Instructions?

### ISSUE THREAD

**Issue by Mentors4EDU** [mavlink/mavlink#1757]
Where are the installation and build instructions for CMake?

**Comment by hamishwillee** [comment]
Since cmake isn't a dependency or requirement for MAVLink, I have to ask why you need them?

**Comment by Mentors4EDU** [comment]
I am confused though how this is compiled because there is a CMakeLists.txt file and a C Make folder but not make file

**Comment by vooon** [comment]
What Makefile you're expecting to see? CMake should generate it, so it shouldn't be under git control. Anyway why do you need it?

**Comment by hamishwillee** [comment]
Closing. The existence of https://github.com/mavlink/mavlink/tree/master/cmake which does not appear to have a use is confusing. I'll see if anyone can work out what it is for, and if no one knows, delete it.
