### ISSUE TITLE
Convenience function mavlink_msg_message_interval_send  needs updating?

### ISSUE THREAD

**Issue by AndKe** [mavlink/mavlink#1820]
I were looking for a simple way to send [MAV_CMD_SET_MESSAGE_INTERVAL](https://mavlink.io/en/messages/common.html#MAV_CMD_SET_MESSAGE_INTERVAL) (511)
I was thrown off by the function mavlink_msg_message_interval_send which looked like what I needed, but then it produces a command 244 (which does not seem to be used anywhere)

given that 244 is "gone" (?) one could consider to update/change it to produce the MAV_CMD_SET_MESSAGE_INTERVAL

**Comment by hamishwillee** [comment]
No.

If you want to set a message interval you send the [MAV_CMD_SET_MESSAGE_INTERVAL](https://mavlink.io/en/messages/common.html#MAV_CMD_SET_MESSAGE_INTERVAL) command. The specified message will then be streamed at the specified rate.

Sometimes you want to know what the interval should be for a message. In this case you call [MAV_CMD_GET_MESSAGE_INTERVAL](https://mavlink.io/en/messages/common.html#MAV_CMD_GET_MESSAGE_INTERVAL) and it then emits [MESSAGE_INTERVAL](https://mavlink.io/en/messages/common.html#MESSAGE_INTERVAL) (244).

Hope that makes sense.
