### ISSUE TITLE
GCS development with Mavlink1

### ISSUE THREAD

**Issue by ddalkyTokky** [mavlink/mavlink#1832]
Hi community, Im studying for developing GCS system on Android Studio. I want to develop with MavSDK-JAVA. But as I know, this SDK doesnt support MAVLINK v.2 Am i right? and If it does, what issues will be the major problem with using only MAVLINK v.1?

**Comment by hamishwillee** [comment]
MAVSDK Java supports MAVLink v2. Questions related to MAVSDK should be addressed on the MAVSDK repo - this is the MAVLink repo.

To answer your question, most systems now have moved to MAVLink v2. Mavlink v1 has limited use far fewer messages are supported. In other words, you can do specific things, but lots of messages simply won't work.

**Comment by ddalkyTokky** [comment]
Oh.. My mistake xD Thank you for your help!
