### ISSUE TITLE
Documentation: wind_cov

### ISSUE THREAD

**Issue by flybrianfly** [mavlink/mavlink#1838]
For the [WIND_COV](http://mavlink.io/en/messages/common.html#WIND_COV) (wind covariance) message, I think the units of `horiz_accuracy` and `vert_accuracy` should be `m/s`, not `m`.

Field Name | Type | Units | Description
-- | -- | -- | --
horiz_accuracy | float | m | Horizontal speed 1-STD accuracy
vert_accuracy | float | m | Vertical speed 1-STD accuracy

**Comment by hamishwillee** [comment]
@flybrianfly Possibly. @julianoes Who would be best person to ask about this?

BTW, PX4 just sets this to 0 in https://github.com/PX4/PX4-Autopilot/blob/master/src/modules/mavlink/streams/WIND_COV.hpp#L82

**Comment by flybrianfly** [comment]
Great, thanks!
