### ISSUE TITLE
Missing values for a few enums?

### ISSUE THREAD

**Issue by haakoo** [mavlink/mavlink#185]
I've recently started using Mavlink.Net (generates C# code from the XML-definitions), and came across something strange today. Three of the generated enums all have value = 0 for all the enum values. I looked at the definitions files I'm using (common.xml and ardupilotmega.xml) and in common.xml I found that the three enums don't have values assigned to enum entries.

The three enums are:
- MAVLINK_DATA_STREAM_TYPE
- MAV_STATE 
- MAV_CMD_ACK

Is this intentional?

Here' the beginning of MAV_STATE

``` xml
<enum name="MAV_STATE">
    <entry value="0" name="MAV_STATE_UNINIT">
        <description>Uninitialized system, state is unknown.</description>
    </entry>
    <entry name="MAV_STATE_BOOT">
        <description>System is booting up.</description>
    </entry>
    ...
</enum>
```

Should all these three enums have running numbering starting from 0?

**Comment by amilcarlucas** [comment]
No that was not intentional and has been corrected.

This can be closed now

**Comment by amilcarlucas** [comment]
@LorenzMeier please close this.
