### ISSUE TITLE
Error in generated C++ headers

### ISSUE THREAD

**Issue by fisian** [mavlink/mavlink#1853]
I generate headers for C++ with the command `mavgen.py --lang=C++11 --wire-protocol=2.0 --output=include/v2.0 message_definitions/v1.0/all.xml`.

However, there is a problem in the header `common/common.hpp`.
For the enum `MAV_FTP_ERR` a member `EOF = 6` is generated.
This causes errors when including the header because `EOF` is a macro defined in cstdio / stdio.h.

I wasn't sure if this should be an issue here or in the pymavlink repo.

**Comment by hamishwillee** [comment]
Thanks @fisian - it's an issue here, at least initially. This is what I get generated:

.hpp
```cpp
/** @brief MAV FTP error codes (https://mavlink.io/en/services/ftp.html) */
enum class MAV_FTP_ERR
{
    NONE=0, /* None: No error | */
    FAIL=1, /* Fail: Unknown failure | */
    FAILERRNO=2, /* FailErrno: Command failed, Err number sent back in PayloadHeader.data[1].
		This is a file-system error number understood by the server operating system. | */
    INVALIDDATASIZE=3, /* InvalidDataSize: Payload size is invalid | */
    INVALIDSESSION=4, /* InvalidSession: Session is not currently open | */
    NOSESSIONSAVAILABLE=5, /* NoSessionsAvailable: All available sessions are already in use | */
    EOF=6, /* EOF: Offset past end of file for ListDirectory and ReadFile commands | */
    UNKNOWNCOMMAND=7, /* UnknownCommand: Unknown command / opcode | */
    FILEEXISTS=8, /* FileExists: File/directory already exists | */
    FILEPROTECTED=9, /* FileProtected: File/directory is write protected | */
    FILENOTFOUND=10, /* FileNotFound: File/directory not found | */
};

//! MAV_FTP_ERR ENUM_END
constexpr auto MAV_FTP_ERR_ENUM_END = 11;
```

.h
```c
/** @brief MAV FTP error codes (https://mavlink.io/en/services/ftp.html) */
#ifndef HAVE_ENUM_MAV_FTP_ERR
#define HAVE_ENUM_MAV_FTP_ERR
typedef enum MAV_FTP_ERR
{
   MAV_FTP_ERR_NONE=0, /* None: No error | */
   MAV_FTP_ERR_FAIL=1, /* Fail: Unknown failure | */
   MAV_FTP_ERR_FAILERRNO=2, /* FailErrno: Command failed, Err number sent back in PayloadHeader.data[1].
		This is a file-system error number understood by the server operating system. | */
   MAV_FTP_ERR_INVALIDDATASIZE=3, /* InvalidDataSize: Payload size is invalid | */
   MAV_FTP_ERR_INVALIDSESSION=4, /* InvalidSession: Session is not currently open | */
   MAV_FTP_ERR_NOSESSIONSAVAILABLE=5, /* NoSessionsAvailable: All available sessions are already in use | */
   MAV_FTP_ERR_EOF=6, /* EOF: Offset past end of file for ListDirectory and ReadFile commands | */
   MAV_FTP_ERR_UNKNOWNCOMMAND=7, /* UnknownCommand: Unknown command / opcode | */
   MAV_FTP_ERR_FILEEXISTS=8, /* FileExists: File/directory already exists | */
   MAV_FTP_ERR_FILEPROTECTED=9, /* FileProtected: File/directory is write protected | */
   MAV_FTP_ERR_FILENOTFOUND=10, /* FileNotFound: File/directory not found | */
   MAV_FTP_ERR_ENUM_END=11, /*  | */
} MAV_FTP_ERR;
#endif
```

@julianoes Thoughts? Solutions?

**Comment by julianoes** [comment]
The `enum class` is namespaced correctly, however, the string EOF is presumably still already defined by a macro.

Have you tried including `<cstdio>` instead of `stdio.h`?

**Comment by hamishwillee** [comment]
@fisian Ping re comment above ^^^

**Comment by fisian** [comment]
I don't include `<cstdio>` or `stdio.h` myself. The error occurs even when I try to compile a file that only includes the generated header.

I also don't know from where exactly the EOF macro is included or where it is defined.
From a quick investigation it seems that it is indirectly included by multiple headers of the standard library (of which the first occurence in the generated file is `<sstream>`).

**Comment by danx0r** [comment]
I have this error - extra */  in 2 places in vehicle_command__struct.h - presume C++ compiler was more forgiving previously

**Comment by hamishwillee** [comment]
@julianoes Mean anything to you?

**Comment by julianoes** [comment]
Can someone create a minimal example to reproduce? That would help me understand how it all comes together, thanks.

**Comment by fisian** [comment]
I don't know what the error is @danx0r describes. It's not the issue I reported and I don't have anything called vehicle_command. A quick search suggests it is specific to the PX4 firmware.

**Comment by spectre-solutions** [comment]
Hi all. The problem which @fisian  described still exists. 
I propose a solution here: https://github.com/ArduPilot/pymavlink/pull/761
Should I create an Issue for pymavlink? 
Thanks

**Comment by hamishwillee** [comment]
@spectre-solutions Thanks for that - https://github.com/ArduPilot/pymavlink/pull/761 is the right place to post this. It may take a while for the team to look at it though.

**Comment by spectre-solutions** [comment]
Issue was fixed in pymavlink https://github.com/ArduPilot/pymavlink/issues/762
Are there some rules about updating pymavlink submodule? We would be thankful if someone could do this.

**Comment by hamishwillee** [comment]
@spectre-solutions No rules other than basic sanity check. Anyone can create a PR to update - which I have done and merged in https://github.com/mavlink/mavlink/pull/1940

**Comment by hamishwillee** [comment]
Thanks for fixing this up!

**Comment by spectre-solutions** [comment]
Great, thank you as well!
