### ISSUE TITLE
Dart support?

### ISSUE THREAD

**Issue by penzi520** [mavlink/mavlink#1907]
can support Dart?

**Comment by hamishwillee** [comment]
Dart is not supported by the project, but there is nothing to stop others writing Dart libraries. Can't comment on how compliant they might be. For example: https://github.com/nus/dart_mavlink

The list of supported languages is here https://mavlink.io/en/#mavlink-project-generatorslanguages

**Comment by LiangHuangBC** [comment]
Is it possible to build a controller like QGC by flutter?  Any helpful repo or link? Thanks a lot. @hamishwillee

**Comment by hamishwillee** [comment]
I have no idea. All I would be doing if I sent you a link would be googling. But if I had to start anything like that, I'd look, at MAVSDK.

**Comment by LiangHuangBC** [comment]
Thanks. MAVSDK is fine.

**Comment by explorer-source** [comment]
@LiangHuangBC have you made it work? I'm also trying to build custom QGC with flutter
