### ISSUE TITLE
Mavlink versioning? Need to update QGC for Remote ID implementation

### ISSUE THREAD

**Issue by Davidsastresas** [mavlink/mavlink#1953]
Hello, I saw it's been a long time since we don't have tags in mavlink. Are we following any kind of versioning? 

We are attempting to update mavlink on QGC in order to include Remote ID support:

https://github.com/mavlink/qgroundcontrol/pull/10600

 and we are not sure if there is something like mavlink "stable".

Thank you!

**Comment by hamishwillee** [comment]
PS The Remote ID stuff in MAVLink hasn't changed since the US government certification requirement. This is the same version PX4 and ArduPilot implemented against (though I am not sure of the state of their implementations).

**Comment by Davidsastresas** [comment]
Thank you very much for your explanations, all you said makes sense. Thanks!
