### ISSUE TITLE
mavlink_rc_channels_override_t unable to cover successfully

### ISSUE THREAD

**Issue by yuyuasd** [mavlink/mavlink#1964]
Hello, I want to use mavlink to send an rc3 to 1500 command, but with this command, the raw value read by the heartbeat does not change. Is there any good solution?Thank you very much.

```

void Dialog::on_RC_3_1000_clicked()
{
    mavlink_message_t message;
    mavlink_rc_channels_override_t rc_override;
    // 设置油门值为0%

    rc_override.chan3_raw = 1500;
    // 填充消息
    mavlink_msg_rc_channels_override_encode(1, 1, &message, &rc_override);
    // 发送消息
    QByteArray buff(2041,0);
    uint16_t len = mavlink_msg_to_send_buffer((uint8_t *)buff.data(), &message);
    mSerialPort.SendDataBuf(buff, len);
}
```

**Comment by hamishwillee** [comment]
I think your question is "why doesn't sending [RC_CHANNELS_OVERRIDE](https://mavlink.io/en/messages/common.html#RC_CHANNELS_OVERRIDE) with channel 3 value set to 1500 change the output value. Is that right? (I'm not sure what the heartbeat has to do with this).

If so, the answer depends on what flight stack you are using. Are you sure this message is supported on your flight stack. I would expect it to be on ArduPilot, but I am not sure it works on PX4.

I suggest you repost this query on the discussion area for the flight stack you are using.
