### ISSUE TITLE
Upload Rallypoint using MAVRallyLoader (pymavlink)

### ISSUE THREAD

**Issue by SBHKoda** [mavlink/mavlink#1975]
Hi all, I tried to create and upload a rallypoint using the MAVRallyLoader class but it doesn't work, has anyone already had this same problem? I have used MAVWPLoader for normal waypoints and it works fine

**Comment by auturgy** [comment]
suggest this be transferred to https://github.com/ardupilot/pymavlink

**Comment by hamishwillee** [comment]
@SBHKoda Are you still interested in this? If so, can you recreate at the link above ^^ and cross link here?

**Comment by hamishwillee** [comment]
I'm closing this as we can't proceed without an active stakeholder. @SBHKoda If you want to proceed this, please recreate in https://github.com/ardupilot/pymavlink
