### ISSUE TITLE
Hi, Can anyone help  me build this project?

### ISSUE THREAD

**Issue by kryptoniancode** [mavlink/mavlink#1999]
I am wrtiting thesis for my degree. I have written but it needs to include this also. But I am not understanding how can I build this I have tried to build but gettings error?
Any help or guide will be appreciated?

https://github.com/aniskoubaa/mavsec

**Comment by hamishwillee** [comment]
Building this project means "generating a library of functions from some XML dialect file in a particular programming language". The instructions to do that are in https://mavlink.io/en/getting_started/

If you want to then use the generated library, building it depends on what programming language you are using. Assuming you are using C, you can look at the ardupilot implementation to see how it is built or read the other docs.

If you want more specific support, please outline the flight stack and xml you are building, what you have tried and the errors you are getting. Closing for now.
