### ISSUE TITLE
Use unions where multiple data type variables are used

### ISSUE THREAD

**Issue by Susurrus** [mavlink/mavlink#2]
Working with the parameter protocol is rather difficult because unions aren't already provided for messages that support multiple data types, specifically MAVLINK_MSG_ID_PARAM_SET and MAVLINK_MSG_ID_PARAM_VALUE. Their supporting message structs, mavlink_param_set_t and mavlink_param_value_t, should use the mavlink_param_union_t for their param_value element. This would make translating the data between different data types trivial instead of laborious as it is right now.

**Comment by LorenzMeier** [comment]
Closing as stale.
