### ISSUE TITLE
offsetof() not declared when using MAVLINK_MESSAGE_INFO

### ISSUE THREAD

**Issue by Susurrus** [mavlink/mavlink#200]
`mavlink_types.h` should `#include <stddef.h>` to make sure other files can compile the `MAVLINK_MESSAGE_INFO` macro.

**Comment by amilcarlucas** [comment]
I did not need that in my SW. Can you please elaborate why the MAVLINK_MESSAGE_INFO needs that ?

**Comment by Susurrus** [comment]
I don't remember the original problem and I don't use this software anymore. If nobody else has run into this, let's close it as Won't Fix, Can't Reproduce.
