### ISSUE TITLE
Adding support to somehow link mavlink cameras and mavlink gimbals?

### ISSUE THREAD

**Issue by Davidsastresas** [mavlink/mavlink#2006]
In the latest days this matter was raised with @rmackay9 and @julianoes . In gimbals with mavlink cameras this could be very useful, because some settings from gimbal could affect cameras and vice-versa. The most obvious case is the "click and point" feature getting included in QGC soon. This feature needs to know the FOV of the camera to scale the clicks appropiately, so if QGC is receiving telemetry from a mavlink camera it could deal with this appropiately.

This could be also interesting if we bring back support for camera pan/tilt for joysticks connected to QGC, for the same reason above, we would want much less speed at high levels of zoom. And this is also true for camera/gimbal management within Autopilot firmware for the same reason, to auto scale manual pan/tilt control.

It could be also useful if at some point we enable more advanced features like that cool feature DJI has of selecting an area of interest in the video feed to take a "super resolution" photo, where camera is zoomed in and gimbal is moved to take high resolution pictures of the selected area of interest, that could be later merged in a super high res picture. This is a random example but for something like this it is interesting as well that whoever is managing this ( GCS, companion computer, autopilot ) will need to manage camera triggers and gimbal movement at the same time, and will need information about FOV, etc.

@julianoes suggested extending a field in camera and gimbal information that could link them to one another, and this could be the component id of the gimbal/camera associated with it. I like this idea very much.

We thought it was worth bringing this discussion to get more input.

Thanks!

**Comment by auturgy** [comment]
Linking to https://github.com/mavlink/mavlink/issues/1678

**Comment by rmackay9** [comment]
In ArduPilot at the moment we always assume that the camera and gimbal instances match.  So camera1 is in gimbal1.  This has worked so far because the number of users is small and we haven't yet hit complaints from users where there are multiple cameras within a single gimbal.

Adding a field to CAMERA_INFORMATION and GIMBAL_MANAGER_INFORMATION seems OK to me although I guess in the multiple-camera-in-single-gimbal case the gimbal-device-information would only have the first camera in the field.  Perhaps it is sufficient to only add the gimbal_id to the CAMERA_INFORMATION message assuming there is no way that a single camera could be in multiple gimbals.

**Comment by Davidsastresas** [comment]
> In ArduPilot at the moment we always assume that the camera and gimbal instances match. So camera1 is in gimbal1. This has worked so far because the number of users is small and we haven't yet hit complaints from users where there are multiple cameras within a single gimbal.
> 
> Adding a field to CAMERA_INFORMATION and GIMBAL_MANAGER_INFORMATION seems OK to me although I guess in the multiple-camera-in-single-gimbal case the gimbal-device-information would only have the first camera in the field. Perhaps it is sufficient to only add the gimbal_id to the CAMERA_INFORMATION message assuming there is no way that a single camera could be in multiple gimbals.

It makes sense!

**Comment by hamishwillee** [comment]
Are there any other gimbal payloads than cameras that might need to know what gimbal they are attached to? If so then perhaps the information would be better in the gimbal (what is component id of my payload, if any).

This feels like a bandaid. As per the discussion @auturgy linked to above, can we work through the combined gimbal/camera case to see if there are any other holes we can fix at the same time?

**Comment by rmackay9** [comment]
Rangefinders (aka lidar, sonar, etc) can also be mounted in a camera gimbal mount.  For example some ViewPro and Siyi camera gimbals also include a lidar.  I suspect that some users would like to see a distance reading easily on the camera/gimbal control screen if their camera gimbal has a lidar.

I guess the solution is to add something to the DISTANCE_SENSOR message (seems like a bad idea) or perhaps add a field to [CAMERA_FOV_STATUS](https://mavlink.io/en/messages/common.html#CAMERA_FOV_STATUS)

**Comment by auturgy** [comment]
Spotlights/IR illuminators also get mounted to gimbals from time to time (with or without cameras), as do directional antennas.

**Comment by hamishwillee** [comment]
> BTW, I think adding a gimbal_id field to the CAMERA_INFORMATION message is a good solution and it's better than just a "band-aid".

@rmackay9 I think it's a good solution too. I'm just worried that we'll add this and realize that there are other things we need to do, and that this solution doesn't work well with them. In other words, I don't want to have to change messages unless we're sure.

**Comment by Davidsastresas** [comment]
The idea of more devices like rangefinders, iluminators, etc makes sense, but do they really need to be linked for any particular reason to the gimbal?

The use case for linking the camera is to adjust movement based on FOV. Any camera with zoom will really need the gimbal to auto adjust its sensitivity for manual control for the UX to be reasonably good. This is specially true with that click and point feature we are working over for QGC, as it really depends on FOV knowledge to work at all.

But in the case of the rest of potential devices attached to a gimbal like iluminators, rangefinders, etc is there really any use to link them to a gimbal? My understanding is that such sophisticated payloads should probably have mavlink implemented properly, and if this is the case, just sending the messages corresponding to these extra sensors with its compid would be enough for the rest of the nodes of the system to understand such devices belong to such gimbal.

Is there any benefit for such devices to be associated with a gimbal at their mavlink messages level?

**Comment by hamishwillee** [comment]
> Is there any benefit for such devices to be associated with a gimbal at their mavlink messages level?

Sounds reasonable. And if it becomes a problem, then presumably a similar pattern could be followed to associate them with a gimbal. 

> I think what Randy suggested about adding a field to CAMERA_INFORMATION should fix the issue here.

This does sound like a good solution and I don't have a better one. Please create an upstream PR for review.

@rmackay9 @Davidsastresas 

At the end of this work do you think you could help write a doc on integrated camera/gimbals as per #1678 ? I think the docs for gimbal and for camera are fine on their own, but I don't have a view on how the two systems integrate. Since you're doing the work you will have a good view on how this works in practice.

**Comment by auturgy** [comment]
closed by linked PR
