### ISSUE TITLE
support flutter/dart for cross-platform development

### ISSUE THREAD

**Issue by zhangchuanbbs** [mavlink/mavlink#2051]
Do you consider generating header files for Flutter/Dart for cross-platform development

**Comment by hamishwillee** [comment]
If you want to contribute such a library that would be welcome - as far as I know no one is developing such a library

**Comment by hamishwillee** [comment]
Or to be more precise, the project isn't actively working on such a library as far as I know. But others outside may be - see https://github.com/nus/dart_mavlink
