### ISSUE TITLE
How to generate static link library of MAVLINK？

### ISSUE THREAD

**Issue by zhangteng0526** [mavlink/mavlink#2071]
The current C library generates .h header files. What should I do if I want to generate a static library? I hope to get your suggestions and help, thank you

**Comment by hamishwillee** [comment]
Sorry for the delay. Why do you want to? @julianoes is this something that is supported or we can hint at?

**Comment by julianoes** [comment]
There isn't really a static or dynamic library for a header only library. Why would you need that?

**Comment by hamishwillee** [comment]
Closing due to no response. THanks Julian.
