### ISSUE TITLE
Discussion: Separate out Camera Sensors, Camera Channels and Camera Outputs

### ISSUE THREAD

**Issue by nexton-winjeel** [mavlink/mavlink#2084]
Following from #2079, I want to discuss the various considerations in describing camera payloads with multiple sensors, without derailing #2079.

The current [Camera Protocol](https://mavlink.io/en/services/camera.html) appears to mostly assume a camera with a single sensor. There are some gaps that make it harder to work with camera payloads with multiple sensors.

At a high level, payloads can be modelled as consisting of:
* One or more _Sensors_: the image sensor/lens combos that capture raw imagery.
* Zero or more _Channels_: the conversion of raw sensor imagery into encoded video.
* Zero or more _Outputs_: the transport stream sending out the encoded video.

In the current Camera Protocol:
* _Sensors_ mostly map to [`CAMERA_INFORMATION`](https://mavlink.io/en/messages/common.html#CAMERA_INFORMATION)
* The combination of _Channel_ and _Output_ mostly map to [`VIDEO_STREAM_INFORMATION`](https://mavlink.io/en/messages/common.html#VIDEO_STREAM_INFORMATION)

A brain dump of comments that I'll clean up later:
* _Sensors_:
    * May need to be split out into two components, Sensor and Len, particularly if active lenses are used.
* _Channels_:
    * Often a one-to-one mapping to _Sensors_
    * Can be a fusion of multiple _Sensors_, e.g. Picture-In-Picture (PIP), Blending
    * Often down-sampled (image size and/or frame-rate) from the _Sensor_ imagery
    * Image tracking usually happens at this level.
* _Outputs_:
    * Can be down-sampled again from the _Channel_ imagery 
* Commands:
    * Depending on the payload, image capture can occur on any of the _Sensors_, _Channels_ or _Outputs_.
* Other:
    * In payloads with multiple _Sensors_, each sensor could be published as a separate MAVLink camera component. But this doesn't help when the commands need to be addressed to the payload, rather than the cameras, e.g.:
        * If a payload can only snapshot the current video stream, does sending a `CAMERA_IMAGE_CAPTURE` command to the camera change the active video stream of the payload?
        * If a payload can only capture imagery from one camera at a time, what happens if a capture is requested on a second camera? Temporarily rejected? Cancel the first capture and start the new capture? Implementation defined?

**Comment by nexton-winjeel** [comment]
FYI: @hamishwillee, @rmackay9, @MatejFranceskin, @dogmaphobic

**Comment by nexton-winjeel** [comment]
Also relates to #1678.

**Comment by hamishwillee** [comment]
FWIW we ended up going with the solution in #2079. I'm going to close this - thanks for your input @nexton-winjeel . FWIW I like this kind of separation and thinking - we've got this as a record if there is interest in iterating the API in future.
