### ISSUE TITLE
/mavlink_msg_protocol_version.h:207:108: error: ‘mavlink_status_t’ has not been declared

### ISSUE THREAD

**Issue by abdul-mannan-khan** [mavlink/mavlink#2140]
I am getting this message once I tried to compile

`/mavlink_msg_protocol_version.h:207:108: error: ‘mavlink_status_t’ has not been declared`

Any suggestion please? Thank you so much for your response.

**Comment by hamishwillee** [comment]
How are you including mavlink into your project? Instructions are here https://mavlink.io/en/mavgen_c/#get_libraries

Assuming you're using common definitions you'd do:
```c
#include <mavlink/common/mavlink.h>
```

And that should pull everything else you need.

**Comment by 540265466** [comment]
I encountered the same issue as Hamishwillee, and it still hasn't been resolved. Could you please help with a solution?

**Comment by hamishwillee** [comment]
Well then, same question. How are you including it in your project?

**Comment by abdul-mannan-khan** [comment]
No solution yet. Again where and how to include it.

**Comment by hamishwillee** [comment]
@abdul-mannan-khan Did you read my post? https://github.com/mavlink/mavlink/issues/2140#issuecomment-2272380336

I asked if you were linking in the definitions with a line like `#include <mavlink/common/mavlink.h>` .

Unless you confirm that, I'm not going to be able to help you.

**Comment by hamishwillee** [comment]
Closing. Posters not providing enough information for me to be able to help them.

**Comment by jingyang-huang** [comment]
> No solution yet. Again where and how to include it.

Hi, maybe you could try this solution. Find where you get the error, for me it is in `rotors_simulator/rotors_hil_interface/include/rotors_hil_interface/hil_interface.h`
You need to add a line :
```cpp
#ifndef MAVLINK_H
  typedef mavlink::mavlink_message_t mavlink_message_t;
  #include <mavlink/v2.0/common/mavlink.h>
#endif 
```
You would get the modified result:
```cpp
#ifndef MAVLINK_H
  typedef mavlink::mavlink_message_t mavlink_message_t;
  typedef mavlink::mavlink_status_t mavlink_status_t;
  #include <mavlink/v2.0/common/mavlink.h>
#endif 
```
And directly try compile
