### ISSUE TITLE
mavlink_parse_char() always returning 0

### ISSUE THREAD

**Issue by metehand003** [mavlink/mavlink#2149]
Hi I am trying to do a project using MAVLink on STM32F407. I m coding the MCU using STM32CUBE IDE.  When ever I start transmitting the encapsulated data message from the panel. It just stops parsing. Any idea? I included ardupilotmega header into my project

**Comment by hamishwillee** [comment]
It is rude to tag people when you add an issue unless you have a relationship with them that means you know they will be specifically interested. People who are interested in the issue will be looking at the repo and for anyone else your tag is spam.

Closing, as I don't know.
I suggest you post the question on the MAVLink support channel for ArduPilot, providing a buildable link to your code and what you have tried.
