### ISSUE TITLE
can't create libraries for dialect all.xml  

### ISSUE THREAD

**Issue by hbaklan943** [mavlink/mavlink#2182]
running: `python3 -m pymavlink.tools.mavgen --lang=C --wire-protocol=2.0 --output=generated/include/mavlink/v2.0 message_definitions/v1.0/all.xml`

throws:
`FileNotFoundError: [Errno 2] No such file or directory: '/message_definitions/v1.0/loweheiser.xml'`

I guess a dialect file named loweheiser is missing but it is included in ardupilotmega.xml

**Comment by hamishwillee** [comment]
Thanks. Yes, I've got to pull that across - it's new. Will do so this week. In the meantime you could copy it yourself from ArduPilot/mavlink repo

**Comment by hamishwillee** [comment]
Fixed by https://github.com/mavlink/mavlink/pull/2185
