### ISSUE TITLE
Change licensing from LGPL to BSD/MIT/alike

### ISSUE THREAD

**Issue by LorenzMeier** [mavlink/mavlink#225]
Dear contributors,

when we initially started MAVLink, the choice for LGPL was with the intent to be permissive. However, being a header-only library, it has created some confusion with some of the adopters.
Because its a small library intended to be a defacto-standard, neither I nor Andrew Tridgell have any concerns that going to an even more permissive license (like BSD, Apache or MIT) would be an issue - even more, it would meet the original intent of this library much closer than the current LGPL license does. If you have particular proposals (e.g. 3 clause BSD or 2 clause BSD) I'm happy to discuss them. Otherwise I'm going to propose one and then subsequently try to get all contributors to provide feedback wether they are ok with relicensing their contributions under this new license.

**Comment by ryancu7** [comment]
What was the outcome of this? 

I was thinking about using pymavlink in a commercial context but was put off by the header in https://github.com/mavlink/mavlink/blob/master/pymavlink/mavutil.py saying it is licensed as GPL. I know the project overall currently says it is LGPL but the doubt from this header has put me off.

**Comment by LorenzMeier** [comment]
@ryancu7 We are taking licensing seriously and will provide better docs. In general you can expect different licenses for the generator suite itself and generated code, very much like GCC is GPL but you can build proprietary software with it if your input files are proprietary.

**Comment by hholtmann1970** [comment]
I am doing my due diligence on the mavLINK protocol, and as of today (March 12, 2016) and as far as I can tell... the mavLINK protocol is end to end still header only and LGPL.

The bigger concern I have is I want to put fully implement the mavLINK protocl on a bare-metal (no embedded OS or RTOS of any type) autopilot that is one big statically linked object code from one massive code base of pure C code... no partitioning of the memory map for even the "synthetic concept" of a "library of code" section... 

SO..the question is.. whats the bottom line on mavLINK, the LGPL 3.0 (or is LGPL 2.0) and "Embedded Devices".. all compiled on windows using the GCC toolchain.

Latest References and Sources leading me to believe its still LGPL 3.0
https://en.wikipedia.org/wiki/MAVLink
https://github.com/mavlink/mavlink/blob/master/COPYING

Thanks for your consideration.

Heston
