### ISSUE TITLE
Altitude cleanup: WSG84/AMSL

### ISSUE THREAD

**Issue by DrTon** [mavlink/mavlink#256]
Now we have mess with altitude in Firmware/mavlink/qgroundcontrol.
Just to quickly clarify, there are two altitudes:
- WSG84 (the same for other datums): altitude above ellipsoid (problem is that ellipsoid may differ from actual sea level significantly)
- AMSL: altitude above geoid, more precise model

From GPS (ubx) we can get both altitudes.

Need to decide which should be used as primary (or maybe both?) and used in mavlink, uORB topic and qgroundcontrol. And need to do all fixes at once to be consistent to avoid jumping again in future.

**Comment by Ryanf55** [comment]
Is there anywhere in MAVlink that clarifies which Geoid should be used? There's a few that could be used. Is it up to the user to check their GCS, GPS, and terrain all use the same geoid? 
https://en.wikipedia.org/wiki/Earth_Gravitational_Model
