### ISSUE TITLE
mavlogdump.py format JSON failed to work.

### ISSUE THREAD

**Issue by lovesmall** [mavlink/mavlink#272]
while there is no issue to dump with default format on my MAC. When i add "--format json", it will failed:

File "xxx/mavlogdump.py", line 125, in <module>
    data = m.to_dict()
AttributeError: 'DFMessage' object has no attribute 'to_dict'

Any one could help?

**Comment by JamesHarrison** [comment]
This is still an issue, or at least has a related issue. On Python 2.7.9, using `mavlogdump.py` or just trying to use `m._d` etc, I consistently get this error:

```python
Traceback (most recent call last):
  File "dump.py", line 47, in <module>
    print(m.get_fieldnames())
  File "/usr/local/lib/python2.7/dist-packages/pymavlink/DFReader.py", line 89, in __getattr__
    raise AttributeError
AttributeError
```

**Comment by lovesmall** [comment]
This issue is fixed.
