### ISSUE TITLE
pymavlink.generator.mavtestgen doesn't run

### ISSUE THREAD

**Issue by Susurrus** [mavlink/mavlink#291]
Complains about `mavparse.parse_mavlink_xml()` not existing. Also don't see any documentation for this script, so I'm unsure what it's actually supposed to do.

**Comment by flixr** [comment]
I actually just ran into this as well, seems that this was already missing/outdated when `mavtestgen.py` was added with the pymavlink import...
Would be great to know what testsuite one is supposed to use...

**Comment by Susurrus** [comment]
@LorenzMeier You know how the tests work for pymavlink?

**Comment by Susurrus** [comment]
Moving discussion to #327.
