### ISSUE TITLE
mavlogdump.py requires numpy when used

### ISSUE THREAD

**Issue by Susurrus** [mavlink/mavlink#312]
Looks like it imports Quaternion for some reason, which requires numpy. Uncertain why that is, but it's annoying considering I don't have numpy installed as I don't need it for anything else.

**Comment by Susurrus** [comment]
A comment on mavutil.py:20 implies that this is to allow for math expressions in mavlogdump, but I don't see that documented anywhere in the help for it.

**Comment by Susurrus** [comment]
Maybe move these includes out of mavutil.py and into the mavlogdump.py script and the other one and make them conditional includes.

**Comment by mairsbw** [comment]
This has since been fixed. It can be closed.
