### ISSUE TITLE
gen_all.* don't work

### ISSUE THREAD

**Issue by Susurrus** [mavlink/mavlink#331]
Unsure if these are still used, I can't figure out where they should be run from in order to get them to work. Possibly these should be removed?

**Comment by Susurrus** [comment]
If I can get feedback on whether they should just be removed, I can submit a PR for it.

**Comment by LorenzMeier** [comment]
@tridge Feedback? We use the script in the tools directly for auto building.

**Comment by tridge** [comment]
yep, lets remove them
PR welcome, thanks!
