### ISSUE TITLE
Parameter protocol doesn't allow for useful errors

### ISSUE THREAD

**Issue by Susurrus** [mavlink/mavlink#337]
For example I want to limit parameter setting to only certain modes of operation. There is no error emitting/handling built in to the parameter protocol, unlike with the mission protocol. I'd suggest the addition of a PARAM_ACK message with at least the following:
- MAV_PARAM_ERROR - Generic error. Retrying may not resolve this.
- MAV_PARAM_INVALID - The given parameter value is invalid.
- MAV_PARAM_MISSING - The given parameter ID/name does not exist.
- MAV_PARAM_DENIED - Setting parameters is currently disabled.

This message would be an appropriate response to any either PARAM_\* message.

**Comment by Susurrus** [comment]
And since this isn't part of QGC, which has a ridiculously long timeout on their parameter state machine, the user is left with no feedback as to what happened. I imagine more than just me want to implement this.

**Comment by LorenzMeier** [comment]
Sounds like a QGC issue.
