### ISSUE TITLE
/usr/bin/python: No module named tools

### ISSUE THREAD

**Issue by vmayoral** [mavlink/mavlink#344]
Getting this error when compiling the hydro branch of https://github.com/mavlink/mavlink-gbp-release.

I believe it might be related to the fact that new versions of `pyserial` import tools through:
```python
import serial.tools
```

(instead of `import tools`)

**Comment by vooon** [comment]
I think  they need `pymavlink.tools`. Try this patch: https://github.com/mavlink/mavlink-gbp-release/pull/4

**Comment by vmayoral** [comment]
Thanks @vooon, that did it.
