### ISSUE TITLE
Cannot get Mavlink repo to create a Visual Studios Project

### ISSUE THREAD

**Issue by antman1p** [mavlink/mavlink#346]
I have followed all of the instructions.  I have the Mavlink directory in the PYTHONPATH.   I am getting this error:

> > > -m pymavlink.tools.mavgen
> > >   File "<stdin>", line 1
> > >     -m pymavlink.tools.mavgen
> > >                ^
> > > SyntaxError: invalid syntax
> > > 
> > > Using Windows 7 and Python 3.4 .
> > > Does anyone have better instructions for setting up a Mavlink development environment on Visual Studios 2013?

**Comment by LorenzMeier** [comment]
Was never intended that way.
