### ISSUE TITLE
Update the docs for mavlink_parse_char()

### ISSUE THREAD

**Issue by Susurrus** [mavlink/mavlink#36]
The example code looks written for an older version of this function and should be updated.

**Comment by ziyangli** [comment]
I am here to thank @Susurrus for his demo project. I have tried for a whole day to receive a custom defined mavlink message via serial links. It turns out that I have to define my message in pixhawk.xml instead of common.xml, otherwise the receiver just does not recognize the message.

**Comment by RohanKurane** [comment]
I am having issues where when I read a buffer from the socket, I get some bytes and when I try to parse them using mavlink_parse_char(), some of the parsing fails. Some bytes pass parsing and a message is decoded. If I look at the parse_state error in the mavlink_status struct, I see a progression of the channel status (from 2 to 13). Then a byte is parsed. Why is this happening ? Is there anything I need to do to initialize the channel ?

**Comment by roskos** [comment]
@RohanKurane I don't know what your situation is but if you want to use your custom message and read it with mavlink_parse_char(), you need to include your custom message into common.xml and create your header file.
Apparently mavlink_parse_char()  doesn't work when you set it in other xml files.
