### ISSUE TITLE
Paymavlink communication rate maxes out at 25Hz

### ISSUE THREAD

**Issue by scott-eddy** [mavlink/mavlink#369]
I'm trying to merely get data from the pixhawk at 100Hz, specifically I'm interested in the scaled imu data.  To try and set the data rate I'm using the example 'apmsetrate.py' script with the following call:

python apmsetrate.py --baudrate 115200 --device /dev/tty.usbmodem1 --rate 100 --showmessages

However, looking at two consecutive system times I get a rate of about 25Hz.
SYSTEM_TIME {time_unix_usec : 0, time_boot_ms : 8648}
...
SYSTEM_TIME {time_unix_usec : 0, time_boot_ms : 8688}

I'm curious if anyone has been able to communicate with the pixhawk at a faster rate over pymavlink

**Comment by LorenzMeier** [comment]
This is an APM question, wrong issue tracker.
