### ISSUE TITLE
mavcrc gives type error:unsupported operand type(s) for ^: 'str' and 'int'

### ISSUE THREAD

**Issue by georgewhr** [mavlink/mavlink#375]
when I "arm"  the plane. It gives me error below on proxy console:
  File "/usr/local/lib/python2.7/dist-packages/pymavlink/generator/mavcrc.py", line 18, in accumulate
    tmp = b ^ (accum & 0xff)
TypeError: unsupported operand type(s) for ^: 'str' and 'int'

Any idea?

Thanks,
George

**Comment by mairsbw** [comment]
It could be a python3 issue, which version of Python are you using?

**Comment by amilcarlucas** [comment]
Please retest with master. A lot of fixes have went in.
