### ISSUE TITLE
Add timestamp in sensor message SENS_BATMON

### ISSUE THREAD

**Issue by mantelt** [mavlink/mavlink#385]
@philipoe @asm3: How about adding a timestamp to SENS_BATMON? There should be a timestamp message in every sensor message imho.
(https://github.com/mavlink/mavlink/blob/e42d4d1cf7956a5245f3bf40dbdbea6decc0109d/message_definitions/v1.0/ASLUAV.xml#L106)

**Comment by LorenzMeier** [comment]
This is not part of the common message spec. Use BATTERY_STATUS instead.
