### ISSUE TITLE
Clarify MAVLINK_MSG_ID_DATA_STREAM documentation

### ISSUE THREAD

**Issue by Susurrus** [mavlink/mavlink#4]
Right now MAVLINK_MSG_ID_DATA_STREAM isn't clear on how it works as the units of message_rate aren't stated: "The requested interval between two messages of this type". Based on this specification is there a NULL value in it? It'd be useful to be able to turn a stream on where the device uses its default values for transmission or this is a transient message and has no steady transfer rate.

Also the comments don't specify how specific components and MAVs are targeted as this message doesn't have a destination value

**Comment by kd0aij** [comment]
IMHO, ambiguity like this shouldn't be allowed to exist for so long

**Comment by pgiacalo** [comment]
Recent testing with both the Pixhawk/APM and the UDB/MatrixPilot autopilots shows that the field REQUEST_DATA_STREAM.req_message_rate is the requested message rate, in messages/second.
 
If the mavlink team addresses this item, then the documentation should probably say something like, "req_message_rate - the requested message rate, in messages/second".

Providing the units is a simple way to avoid ambiguity and would be a good general practice for all mavlink fields that carry units.

**Comment by LorenzMeier** [comment]
@kd0aij Regarding your comment: There is always the opportunity to file a PR with a documentation update, or to file a comment like @pgiacalo did with the information needed to make a call. I'm not surprised that "it doesn't work" issue reports can get ignored for a long time (until someone steps forward to fund a full-time MAVLink maintainer position).
