### ISSUE TITLE
LANDING_TARGET missing a field

### ISSUE THREAD

**Issue by djnugent** [mavlink/mavlink#431]
I have realized that the LANDING_TARGET is missing an orientation field(yaw). @LorenzMeier @rmackay9 Is it too late to change it? I think I am still the only one who has uses this message so it shouldn't disrupt too much.

**Comment by TSC21** [comment]
@djnugent I also pointed that out too. But, as @LorenzMeier said, it would be good to have a test point for the current implementation of the message and also a working framework on the firmware side (which I'm looking to get in here https://github.com/PX4/Firmware/pull/2446).
Anyhow, a quaternion field would be good in this case. Also I think this won't be a problem, as I think this is still in a dev state. But this is a @LorenzMeier and @rmackay9 call.

**Comment by djnugent** [comment]
@TSC21 I am at the point where I am implementing the firmware side of this message and need orientation.

**Comment by TSC21** [comment]
@djnugent follow up what I sent you above. Right now we need to add the usage. Mainly on the navigator side, so we can issue a landing command and, for example, if it detects valid `LANDING_TARGET` stream, it uses it's position to land. That also requires the usage of `local_position` data so it can land.
Continue the work on PX4/Firmware#2446 if you wish so by cloning the respective branch. Then you can push your modifications to it so discuss them and test their usability.

**Comment by TSC21** [comment]
Also, if you are using ROS, this may become handy: https://github.com/mavlink/mavros/pull/311

**Comment by rmackay9** [comment]
@djnugent, I think if you raise a PR with that field in it, it'll be accepted.  As you say, I don't think there are any consumers yet.  If @TSC21 wants it as well then that's another plus.

**Comment by TSC21** [comment]
For me, it's a green light.

**Comment by mhkabir** [comment]
Please have a look at my comments on the PR.

**Comment by LorenzMeier** [comment]
Closing, to be discussed in the PR.
