### ISSUE TITLE
Request: Loiter Until Command

### ISSUE THREAD

**Issue by labtoast** [mavlink/mavlink#440]
I propose a loiter until command that causes vehicle to wait until system time has elapsed commanded time. This would be used for synchronizing a patrol path or synchronizing movements between multiple vehicles in an open loop manner. 

Inputs:
- Timestamp
- Relative/Absolute Time
- Standard Loiter Parameters

```
<entry value="19" name="MAV_CMD_NAV_LOITER_UNTIL">
                    <description>Loiter around this MISSION until X time</description>
                    <param index="1">Seconds (decimal)</param>
                    <param index="2">0 - time since boot; 1 - absolute time</param>
                    <param index="3">Radius around MISSION, in meters. If positive loiter clockwise, else counter-clockwise</param>
                    <param index="4">Desired yaw angle.</param>
                    <param index="5">Latitude</param>
                    <param index="6">Longitude</param>
                    <param index="7">Altitude</param>
               </entry>
```

**Comment by LorenzMeier** [comment]
This is already present.

**Comment by labtoast** [comment]
I don't see it anywhere in `common.xml`

The closest command is LOITER_TIME  which lets you *delay* by a period of time. The purpose of a LOITER_UNTIL is to synchronize a path with a clock. I would like to perform a movement or action once per minute. The action can take a variable amount of time so a loiter until would synchronize this.

```
<entry value="19" name="MAV_CMD_NAV_LOITER_TIME">
                    <description>Loiter around this MISSION for X seconds</description>
                    <param index="1">Seconds (decimal)</param>
                    <param index="2">Empty</param>
                    <param index="3">Radius around MISSION, in meters. If positive loiter clockwise, else counter-clockwise</param>
                    <param index="4">Desired yaw angle.</param>
                    <param index="5">Latitude</param>
                    <param index="6">Longitude</param>
                    <param index="7">Altitude</param>
               </entry>
```

**Comment by magicrub** [comment]
does time<=0 mean forever? If so then your "command" is to just skip to the next waypoint

**Comment by labtoast** [comment]
`                    <param index="2">0 - time since boot; 1 - absolute time</param>`

I imagined that the inputs would be positive only. It would take UNIX time or time since boot of the flight controller mcu. If the input time was less than current time then the command would skip like you say.  Otherwise, a loiter would occur until the specified time.

**Comment by labtoast** [comment]
Is this feature already present? Can we reopen this issue if not?
