### ISSUE TITLE
Format XML files using xmllint (libxml2 package)

### ISSUE THREAD

**Issue by tcr3dr** [mavlink/mavlink#442]
I started work on upstreaming the MAVLink changes that Solo introduces to ardupilotmega.xml. The biggest issue in several months' of development work, apparently, is whitespace issues that have accumulated.

At least ardupilotmega.xml both upstream and downstream have their own whitespace issues (inconsistent mixed tabs and spaces). Though it makes `git blame` more complicated (requiring the `-w` flag and rendering Github's git blame view less useful), I propose we run all the XML files through `xmllint --format`—with no additional command line flags—and require this for additional changes to these files in message_definitions, to simplify the process in the future.

(Note that this will not block upstreaming of these message definitions, but I wanted to propose this first)

`xmllint` is included with OS X.
`apt-get install libxml2-utils` for Ubuntu distributions.

/cc @tridge

**Comment by mrpollo** [comment]
My biggest issue would be how to enforce this, if we can just ask devs to do it and this is acceptable then I would vote in favor, what do you guys think @LorenzMeier @tridge

**Comment by vooon** [comment]
I think Travis can check formatting. Similar thing done for [rosdistro](https://github.com/ros/rosdistro).

**Comment by tcr3dr** [comment]
Enforcement via a simple Python script (good): https://github.com/ros/rosdistro/blob/master/test/rosdistro_formatting_test.py

**Comment by amilcarlucas** [comment]
This has already been implemented. And the ardupilot fork is now closer to the mavlin/mavlink master as well.


This can be closed now

**Comment by hamishwillee** [comment]
Agreed - yes, is run on travis via script  https://github.com/mavlink/mavlink/blob/master/scripts/format_xml.sh. Thanks @amilcarlucas
