### ISSUE TITLE
Bug in java mavlink generator tool: ${basename} not replaced

### ISSUE THREAD

**Issue by tobawo** [mavlink/mavlink#447]
/* AUTO-GENERATED FILE.  DO NOT MODIFY.
     *
     * This class was automatically generated by the
     * java mavlink generator tool. It should not be modified by hand.
     */
        
    package com.MAVLink;

    import java.io.Serializable;
    import com.MAVLink.Messages.MAVLinkPayload;
    import com.MAVLink.Messages.MAVLinkMessage;
    import com.MAVLink.${basename}.CRC;
    import com.MAVLink.common.*;
    import com.MAVLink.${basename}.*;

**Comment by LorenzMeier** [comment]
Fixed.
