### ISSUE TITLE
STATUSTEXT should be null-terminated, documentation fixed

### ISSUE THREAD

**Issue by wiseman** [mavlink/mavlink#45]
The definition of the "text" field for STATUSTEXT (https://github.com/mavlink/mavlink/blob/f06e7766329bff570cee1ea4b8bfd5b61f5652d9/message_definitions/v1.0/common.xml#L1538 ) says it should not be null-terminated, but there's no other way provided to know how long a text message is.  Ardupilot-mega does null-terminate its status texts.

**Comment by amilcarlucas** [comment]
@LorenzMeier what is the status on this ?

**Comment by LorenzMeier** [comment]
Fixed by adopters. I think acceptable now.

**Comment by wiseman** [comment]
The definition of `STATUSTEXT` in mavlink/message_definitions/v1.0/common.xml still says this, which is still incompatible with current practice as far as I know:
```
<field type="char[50]" name="text">Status text message, without null termination character</field>
```

Am I looking in the wrong place?
