### ISSUE TITLE
Integration Java

### ISSUE THREAD

**Issue by anrubiof** [mavlink/mavlink#466]
Hi! You've shown us how to use libraries in C. How would it be to use them in Eclipse (once generated) with JAVA.

Thanks

**Comment by mairsbw** [comment]
Please only use the Github bug tracker for bugs, features, etc. All user requests should go through the [MAVLink mailing list](https://groups.google.com/forum/#!forum/mavlink).

**Comment by magicrub** [comment]
Not sure what you're asking, either you want java support (duplicate https://github.com/mavlink/mavlink/issues/268) or if you need help so adding it to the github developer todo list is not appropriate - use the mailing list (per @mairsbw ) or gitter.

Either way, this issue needs to be closed.
