### ISSUE TITLE
Document field sorting and MAVLINK_CRC_EXTRA calculation

### ISSUE THREAD

**Issue by willglynn** [mavlink/mavlink#48]
It's not currently possible to implement MAVLink 1.0 by referencing only the specification documents and the message definition XML. The biggest issues I encountered are:

1. Payload fields are re-sorted out of their declaration order when serialized. (Alignment concerns?)
2. There is no information on how to calculate a message type's MAVLINK_CRC_EXTRA byte.

I figured how to interoperate by dissecting `mavparse.py`, but I'm not confident it's 100% correct -- I just know it works for my message types. Regardless, it is my opinion that digging through a reference implementation should not be required to comply with any specification. This information should be extracted and documented.

**Comment by flixr** [comment]
Can this be closed since it is documented on http://qgroundcontrol.org/mavlink/crc_extra_calculation ?

**Comment by TravisWhitaker** [comment]
I just ran into this field reordering nonsense myself, and the link @flixr provided on the CRC in use is broken. Unless I’m missing something it’s still necessary to check the reference implementation to correctly implement this protocol. IMHO these details at least deserve a comment at the top of the spec XML.

**Comment by hamishwillee** [comment]
> I just ran into this field reordering nonsense myself, and the link @flixr provided on the CRC in use is broken. Unless I’m missing something it’s still necessary to check the reference implementation to correctly implement this protocol. IMHO these details at least deserve a comment at the top of the spec XML.

@TravisWhitaker That whole site has been deprecated for some time - all the docs were moved to https://mavlink.io/en/.

The CRC doc was recently updated here: https://mavlink.io/en/serialization.html#crcextra-calculation

What sort of comment were you hoping for on the spec xml (and do you mean the actual XML or the Human readable form? https://mavlink.io/en/messages/
