### ISSUE TITLE
C# generator problem

### ISSUE THREAD

**Issue by harewei** [mavlink/mavlink#482]
I've tried to use mavgenerate.py GUI to generate C# library
XML: mavlink-master/message_definitions/v1.0/ardupilotmega.xml
however, I always get the error not finding source file for CS\common\ByteArrayUtil.cs, FrameworkBitConverter.cs and MavLink.cs, ever though they clearly exist

I tried generating for C and Java, they all work fine.

**Comment by amilcarlucas** [comment]
Retest on master

**Comment by hamishwillee** [comment]
@amilcarlucas This is still valid. I just ran it on Windows:
```
This compiler is provided as part of the Microsoft (R) .NET Framework, but only supports language versions up to C# 5, which is no longer the latest version. For compilers that support newer versions of the C# programming language, see http://go.microsoft.com/fwlink/?LinkID=533240

error CS2001: Source file 'CS\common\ByteArrayUtil.cs' could not be found
error CS2001: Source file 'CS\common\FrameworkBitConverter.cs' could not be found
error CS2001: Source file 'CS\common\Mavlink.cs' could not be found
Error
Error: Compilation failed. (1)
```
It may be that I'm missing some dependency.

**Comment by hamishwillee** [comment]
Duplicated https://github.com/mavlink/mavlink/issues/813

**Comment by amilcarlucas** [comment]
@hamishwillee This is a pymavlink issue that should be reported upstream to https://github.com/ardupilot/pymavlink/issues and closed here

**Comment by hamishwillee** [comment]
Thanks @amilcarlucas - I've cross posted to https://github.com/ArduPilot/pymavlink/issues/151 and will now close.
