### ISSUE TITLE
Airspeed innovation reporting missing from EKF status message

### ISSUE THREAD

**Issue by priseborough** [mavlink/mavlink#502]
We need to add a 'true_airspeed_variance' message after this line:

https://github.com/mavlink/mavlink/blob/master/message_definitions/v1.0/ardupilotmega.xml#L1471

Airspeed innovationis an important indicator of airspeed sensor faults

**Comment by magicrub** [comment]
Sounds good to me. I want to work on pitot tube blockage detection soon so
this still come in handy.

**Comment by LorenzMeier** [comment]
As part of that the message should move to the common message set and see a wider discussion in the overall Dronecode development community so we can make sure we're missing out on as little as possible.

**Comment by LorenzMeier** [comment]
Closing in favour of #511
