### ISSUE TITLE
Overriding RC channels prevents reading true RC input value

### ISSUE THREAD

**Issue by damanfb** [mavlink/mavlink#503]
I am using Roscopter to control my pixhawk with the APM firmware. The program uses the RC override functions in mavlink to send custom RC commands to the FCU. However, I would like to read the RC from the transmitter values, augment them through my offboard computer, and send updated RC values to override the original. Whenever I provide a value to override the RC, the original value from the RC transmitter can no longer be accessed. Is there a way around this?

**Comment by hamishwillee** [comment]
Too old.
