### ISSUE TITLE
ID's for Mavlink enabled OSD's

### ISSUE THREAD

**Issue by lvale** [mavlink/mavlink#513]
AlceOSD is Mavlink aware and it's required to have a MAV_TYPE and a MAV_COMPONENT id.

At the moment the current firmware is working on other ID's that were discussed previously but have been assigned to other uses, so if possible the assignment of ID's is important

Currently the OSD only implements 3 messages:
https://github.com/diydrones/alceosd/blob/master/firmware/alce-osd.X/mavlink.c#L384 and if there’s more interest more can be implemented.

**Comment by tridge** [comment]
thanks Luis, I've pushed a change that adds an _OSD ID, plus a more generic _PERIPHERAL one.
