### ISSUE TITLE
GPL license in several pymavlink files

### ISSUE THREAD

**Issue by cajlarsson** [mavlink/mavlink#514]
It seems not all files had their license header changed to LGPLv3 and stayed GPLv3. Which I assume makes this whole lib GPLv3. I'm sure this is not intentional and all cases had a header that looked something like

    '''
    mavlink python utility functions
    Copyright Andrew Tridgell 2011
    Released under GNU GPL version 3 or later
    '''

**Comment by cajlarsson** [comment]
I'm blind

**Comment by magicrub** [comment]
Not blind?

**Comment by cajlarsson** [comment]
The blindness seems to have only been temporary!

**Comment by peterbarker** [comment]
@cajlarsson On what basis did you believe the pymavlink files should have been relicensed?

I know there was an issue concerning the products of any generation that might occur - an issue to clarify that is here: https://github.com/mavlink/mavlink/issues/549

AFAIK, nobody is seeking to change the licenses within e.g. mavutil.py!

Can this issue be closed?

**Comment by cajlarsson** [comment]
Yes, that is completely verifying for me, thank you!

**Comment by magicrub** [comment]
Ready to close?

**Comment by LorenzMeier** [comment]
Yes - we never discussed or welcomed to relicense the generator / pyMAVLink. The discussion was only ever about clarifying the output.
