### ISSUE TITLE
Need MAV_TYPE_OSD

### ISSUE THREAD

**Issue by ljalves** [mavlink/mavlink#518]
@tridge 
Having MAV_COMP_ID_OSD is great but for the heatbeat I also need to send the MAV_TYPE field.
I can see we have a MAV_TYPE_GIMBAL so I guess a MAV_TYPE_OSD would make sense.

Thanks

**Comment by tridge** [comment]
I think we should add a MAV_TYPE_PERIPHERAL for a generic peripheral

**Comment by ljalves** [comment]
That will work for me.
Will MAV_TYPE_GIMBALL and MAV_TYPE_ADSB get removed? Those seem to fir the the MAV_TYPE_PERIPHERAL type.

**Comment by LorenzMeier** [comment]
Closing as stale.
