### ISSUE TITLE
MAV_CMD_WAYPOINT_USER_1 is not displayed correctly

### ISSUE THREAD

**Issue by Fojtik** [mavlink/mavlink#525]
Dears, before while we agreed that new special waypoint types will be added. These waypoints might have custom payload and QGC will display them transparently.

Unfortunately, when I test to use MAV_CMD_WAYPOINT_USER_1, QGC does not display its position.
https://github.com/mavlink/mavlink/pull/480/files
![customwaypoint](https://cloud.githubusercontent.com/assets/2893993/13805514/9a6cd56e-eb55-11e5-8100-b0590c17e158.jpg)

**Comment by DonLakeFlyer** [comment]
The mavlink pull hasn't not been merged in yet so QGC has not been updated to support this yet.

**Comment by Fojtik** [comment]
OK, thank you for info - are the QGC developpers merging sometimes, or where to ask to merge this? Is this github right platform for merge to ask?

**Comment by DonLakeFlyer** [comment]
I have it on my list of todos. I’ll work to get this pushed through.

**Comment by Fojtik** [comment]
It unfortunatelly does not work, see attached image.
![qgc_custom](https://cloud.githubusercontent.com/assets/2893993/14060146/6da7241e-f35a-11e5-829d-ddfba5372d86.jpg)

**Comment by Fojtik** [comment]
Sorry, custom commands still does not work even in version 3.0.1.

**Comment by magicrub** [comment]
The command should be there, the problem of not working is a px4/ardupilot problem. They're not implemented yet

**Comment by Fojtik** [comment]
To avoid duplicity in discussion I recommend to continue in [https://github.com/mavlink/mavlink/issues/633#issuecomment-252511318](https://github.com/mavlink/mavlink/issues/633#issuecomment-252511318)
