### ISSUE TITLE
Java: uint64_t is not handled correctly

### ISSUE THREAD

**Issue by WickedShell** [mavlink/mavlink#529]
Due to java not having unsigned types we need to promote one size whenever we encounter a unsigned type. Unfortunately there are no primitive types larger then a long, so to handle a long we would need to shove it into a BigInteger, which should be fine as that is part of java.Math and has been around since JDK 1.1.

Does anyone have a concern about using BigIntegers to encode any uint64_t's?

**Comment by LorenzMeier** [comment]
Closing as stale.

**Comment by WickedShell** [comment]
It's not stale. Our should probably be moved to the pymavlink issue, but the issue itself is most definitely not stale.

I do not understand closing issues out that are still issues just because no one has commented on it recently.

**Comment by hamishwillee** [comment]
> I do not understand closing issues out that are still issues just because no one has commented on it recently.

I'm not a fan either. Lets see if there is a policy: #925

In the meantime, could you please move this issue to the right place?
