### ISSUE TITLE
MAV_STATE to add a new state.

### ISSUE THREAD

**Issue by iZhangHui** [mavlink/mavlink#548]
MAV_STATE_ACTIVE means drone system is active, maybe on ground or already airborne.

When getting system status from HEATBEAT message, it couldn't tell that whether the drone is on the ground or in the air, and this information is very useful.

I think we should add a new state like MAV_STATE_ARMED to MAV_STATE, which indicates motors are engaged, ready to fly. The original MAV_STATE_ACTIVE only means system is active and already airborne.

**Comment by amilcarlucas** [comment]
Good point and easy to fix. Can you please create a PR for it ?

**Comment by hamishwillee** [comment]
Closing. There are many ways to get the info.
