### ISSUE TITLE
License clarification of generated MAVLink files

### ISSUE THREAD

**Issue by LorenzMeier** [mavlink/mavlink#549]
I did get approached by companies (startups, not corporate) which were concerned that their use of the MAVLink library in commercial products could be an issue. While our intent is clearly to maximise the proliferation of the protocol, we also want to retain the generator and infrastructure under a copyleft license system.

@tidge and I discussed this and are proposing a model similar to GCC: The "compiler" is GPL licensed, while the resulting compiler output is permissive. This will ensure that improvements to the protocol remain open but it can be bundled into any sort of system. This is in particular relevant for embedded systems.

We would like to ask every pinged author to:

  - Approve or reject the licensing of the *generated* files as MIT
  - When approving clearly indicate that the code used in the templates themselves and utility functions is does not contain third party code which is not MIT compatible (e.g. GPL)

The proposed extension of the license text is:

```
## Exception to the (L)GPL v.3: ##
As an exception, if you use this Software to compile your source code and
portions of this Software, including messages ("the generator output"), are embedded into the
binary product as a result, you may redistribute such product and such
product is hereby licensed under the following MIT license:

Permission is hereby granted, free of charge, to any person obtaining a copy
of the generated software (the "Generated Software"), to deal
in the Generated Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Generated Software, and to permit persons to whom the Generated Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Generated Software.

THE GENERATED SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE GENERATED SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE GENERATED SOFTWARE.
```

**Comment by LorenzMeier** [comment]
@jgoppert @Susurrus @liamstask

**Comment by tridge** [comment]
I think the 2nd para needs to specifically refer to the generated code, otherwise it could be ambiguous if it refers to the generator or the output. The first time I read it I thought "the Software" meant the mavlink package overall. On 2nd reading it was clearer. I'd propose the following to make it clear on first reading:

  Permission is hereby granted, free of charge, to any person obtaining a copy
  of the generated software (the "Generated Software"), to deal
  in the Generated Software without restriction, including without limitation the rights
  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
  copies of the Software, and to permit persons to whom the Generated Software is
  furnished to do so, subject to the following conditions:

note that I also removed the "and associated documentation files" as I'm not actually sure which docs we are referring to there?

**Comment by LorenzMeier** [comment]
Ok, I copied it 1:1 into my original post, so that's now the final proposal.

**Comment by tridge** [comment]
I just realised that the references to "the Software" in the later paragraphs also should be changed to "the Generated Software", otherwise the definition doesn't apply

**Comment by jgoppert** [comment]
I approve and did not use any non MIT compatible code to my knowledge.

**Comment by liamstask** [comment]
Same, I approve the licensing of the generated files as MIT, and did not use any third party code which is not MIT compatible.

**Comment by LorenzMeier** [comment]
@barthess @thomasgubler @dagoodma @geeksville @vooon @dimasad @wiml @malife @rlhartley @ryancu7 @jlecoeur Please let us know each here if you approve the licensing of the generated files as MIT and wether or not you used non-MIT compliant code in your contributions. Thanks!

**Comment by LorenzMeier** [comment]
This would conclude the authors of the C generator files.

**Comment by ryancu7** [comment]
I approve the licensing of the generated files as MIT, and did not use any third party code which is not MIT compatible.

**Comment by jlecoeur** [comment]
I approve the licensing of the generated files as MIT, and did not use any third party code which is not MIT compatible.

**Comment by vooon** [comment]
I approve the licensing of the generated files as MIT, and did not use any third party code which is not MIT compatible.

**Comment by dimasad** [comment]
I strongly approve and haven't used anything that is incompatible with MIT.
In fact, I can't imagine anything that is incompatible with MIT, which is a
great advantage of using permissive licensing for anyone who doesn't have a
law degree. Two simple clauses which are very clear and simple to comply.

~Dimas
Em 29/04/2016 04:10, "Lorenz Meier" <notifications@github.com> escreveu:

**Comment by barthess** [comment]
I approve the licensing of the generated files as MIT, and did not use any third party code which is not MIT compatible.

**Comment by malife** [comment]
I approve the licensing of the generated files as MIT, and did not use any third party code which is not MIT compatible.

-- 
Mariano Lizarraga

**Comment by geeksville** [comment]
Fine by me.  I didn't add any third party code and I'm okay with the stuff I wrote being MIT licensed for generated files.

**Comment by Susurrus** [comment]
This is alright by me as well. I haven't used any third-party code not compatible with the MIT license.

**Comment by LorenzMeier** [comment]
@brucecrevensten Would also be great to have your feedback.

**Comment by thomasgubler** [comment]
I approve the licensing of the generated files as MIT, and did not use any third party code which is not MIT compatible.

**Comment by LorenzMeier** [comment]
@dagoodma @vooon @wiml Would be great to get your feedback as well.

**Comment by dagoodma** [comment]
Lorenz,

Fine by me. I approve the licensing of the generated files as MIT, and to
my knowledge did not use any third party code which is not MIT compatible.

**Comment by ne0fhyk** [comment]
I approve the licensing of the generated files as MIT, and did not use any third party code which is not MIT compatible.

**Comment by arthurbenemann** [comment]
+1 for the Java generator
