### ISSUE TITLE
Java: lost packet count doesn't account for sysid

### ISSUE THREAD

**Issue by WickedShell** [mavlink/mavlink#552]
This causes large lost jumps when a 3dr radio interjects packets, or even a different talker is on a link.

**Comment by amilcarlucas** [comment]
@WickedShell is this a mavlink issue ? or is it an upstream pymavlink issue https://github.com/ardupilot/pymavlink/issues ?

**Comment by WickedShell** [comment]
It was a pymavlink issue, but this was opened before the split I believe. Either way I believe I crudely worked around the core problem in #569 so this can be closed.
