### ISSUE TITLE
Proposal MAV_CMD_NAV_VTOL_LAND param #2 acceptance radius

### ISSUE THREAD

**Issue by sanderux** [mavlink/mavlink#605]
Back transitions tend to overshoot the VTOL_LAND waypoint due to the back duration duration.
A well planned mission could avoid this if the acceptance radius for this item could be set.

For a regular waypoint param2 is specified as the acceptance radius, i propose this is extended to the VTOL_LAND command. 

/cc @tridge @LorenzMeier

**Comment by amilcarlucas** [comment]
This is AFAIK implemented in master.

IMHO this can be closed now.

**Comment by sanderux** [comment]
Obsolete issue indeed
