### ISSUE TITLE
Fix Python 3 (Py3K) support

### ISSUE THREAD

**Issue by dimasad** [mavlink/mavlink#610]
According to issue #35, mavlink already supports Python 3. However, installing the master branch from source I could see that many modules are incompatible:
- several incompatible raise statements in `genxmlif` and `minixsv`, generating syntax errors,
- print satements in `genxmlif`, generating syntax errors,

Python 2.7 is legacy, now more than ever. We should aim for continuous python 3 support. I can start fixing some of these issues, if more people can help it would be appreciated.

**Comment by markrjr** [comment]
Why hasn't this been merged yet?

**Comment by magicrub** [comment]
the generator project has moved, it is now at https://github.com/ArduPilot/pymavlink and Python v3 support was added a month ago (and since improved) via PR https://github.com/ArduPilot/pymavlink/pull/10

I suggest this issue be closed.
