### ISSUE TITLE
mavlink_conversions.h compile issue

### ISSUE THREAD

**Issue by ssepa001** [mavlink/mavlink#627]
So I am trying to compile a simple send program in Arduino but I get the following error with regards to the library : 

mavlink_conversions.h:38:1: error: 'MAVLINK_HELPER' does not name a type
\libraries\mavlink/mavlink_conversions.h:67: error: expected constructor, destructor, or type conversion before 'void'

Any ideas ?

**Comment by magicrub** [comment]
Are you compiling via python?

**Comment by ssepa001** [comment]
Yes

**Comment by amilcarlucas** [comment]
please include just include one single file. For example minimal.h do not include common.h explicitly.

This is not a bug. IMHO This can be closed now

**Comment by hamishwillee** [comment]
Thanks @amilcarlucas . Closing.
