### ISSUE TITLE
MAV_CMD_WAYPOINT_USER_1 is not displayed correctly - #2

### ISSUE THREAD

**Issue by Fojtik** [mavlink/mavlink#633]
Sorry, custom commands still does work not work even in version 3.0.1.
[https://github.com/mavlink/mavlink/issues/525](https://github.com/mavlink/mavlink/issues/525)

**Comment by magicrub** [comment]
This command has been add to the protocol correctly 7 months ago so the problem exists in the autopilot implementation. Please close this issue here and make a new issue on the px4/ardupilot issues list for developers, or you, to implement the feature.

**Comment by Fojtik** [comment]
Why?
I am not interested in px4/ardupilot implementation. 

I want QGroundControl to display position correctly. Nothing else. QGC displays currently a garbage, all waypoints alligned to a line.

I can provide to anybody IP connection to a simulated plane that uses MAV_CMD_WAYPOINT_USER_1. Very old versions of QGroundcontrol displayed position without any limitation neglectiong to point type.

**Comment by magicrub** [comment]
So maybe a problem with qgc? Its not a problem with MAVLink, the protocol had add it. There is nothing to change in this repo to help you.

**Comment by Fojtik** [comment]
Sorry, where to post problems with QgroundControl GUI? I guessed that this is right github.
I will repost my issue there and close this.

**Comment by magicrub** [comment]
https://github.com/mavlink/qgroundcontrol

**Comment by Fojtik** [comment]
Thank you very much, I do not know that there are two different issues list.
I have posted the task here:  [https://github.com/mavlink/qgroundcontrol/issues/4124](https://github.com/mavlink/qgroundcontrol/issues/4124)
And of course I am going to close this.
