### ISSUE TITLE
Modern Ground Truth message

### ISSUE THREAD

**Issue by mhkabir** [mavlink/mavlink#660]
@LorenzMeier, we need a new message which can be used to transfer ground truth (like ATT_POS_MOCAP, but with velocities). I found that we don't have anything for it when comparing trajectories from VIO vs. onboard estimates.

Any objections?

**Comment by ecmnet** [comment]
Maybe it makes sense to make the source of ground truth configurable.

**Comment by mhkabir** [comment]
@Eike can you elaborate? What do you mean by configurable?

**Comment by ecmnet** [comment]
@mhkabir e.g. I would like to use RTK GPS as ground truth in local frame outdoors.

**Comment by LorenzMeier** [comment]
Closing as stale - please re-open if still relevant.
