### ISSUE TITLE
Add Testing Branch Message Generation

### ISSUE THREAD

**Issue by jgoppert** [mavlink/mavlink#668]
It is currently very difficult to test out new messages. It would be nice if branches could be created that would trigger branch creation on the generated library repos as well so we could just checkout the generated library  branch and test new messages (in QGC/ PX4 etc.) without destabilizing master.

**Comment by jgoppert** [comment]
Alternatively, we could add an easier mechanism for incorporation of customer mavlink messages and also use that for testing.

**Comment by LorenzMeier** [comment]
Closing as stale.
