### ISSUE TITLE
Add enumerator in common.xml for mavlink_set_position_target

### ISSUE THREAD

**Issue by PeterQFR** [mavlink/mavlink#669]
The type_mask for the mavlink_set_position_target is poorly defined including that the bit numbering in the description starts at 1 instead of 0 and that the values of the highest nibble are not well defined (and are actually poorly implemented in px4 FC).

Add an enumerator in the common.xml to define these masks and provide a common enum for use of the bitmask.
@dagar

**Comment by amilcarlucas** [comment]
Good point, and very simple to fix. Can you please provide a pull request ?

**Comment by amilcarlucas** [comment]
Fixed in #997
