### ISSUE TITLE
mavgenerate.py future module not found!!

### ISSUE THREAD

**Issue by badaniels** [mavlink/mavlink#680]
Hi,

I'm trying to add a mavlink msg and also change a commons message. I'm now trying to convert the xml file on my mac but whenever I try and run the mavgenerate.py file it says that a future module was not found. I've downloaded future-0.16.0 for python but it stills say the same. 

WTF is happening or going wrong. Why can't I just write or amend the .h files for mavlink messages. 

Thanks in advance.

**Comment by cclauss** [comment]
```
$ python -V
$ pip -V
$ pip install --upgrade future  # http://python-future.org/quickstart.html
```

**Comment by badaniels** [comment]
Thanks. I'll try that this afternoon. Is it possible to just write a .h file, or do you have to write the xml and then convert it?
