### ISSUE TITLE
Can someone help in open a serial port?

### ISSUE THREAD

**Issue by nadavkehila** [mavlink/mavlink#686]
Hi there!

I am new in this field and trying to send commands to my drone via Mavlink but it doesn't seem to work.

On YouTube I saw how to open a serial port but it is always showing how to do so between 2 computers and not between my computer to the drone. 

**So, can someone please guide me through creating the ARM command in C++ all through the command itself, the serial port creation and use, and header files needed for the project?**

Will be forever grateful for the kind helper!

**Comment by amilcarlucas** [comment]
Please post your support question on the support forum. This is only for bug reports and feature requests.

AFAIK this can be closed now
