### ISSUE TITLE
win7 x64 sp1, python 2.7.3,can't generate the mavlink code

### ISSUE THREAD

**Issue by wmx-github** [mavlink/mavlink#689]
win7 x64 sp1, python 2.7.3,can't generate the mavlink code, 
it runs quicklly  and nothing happend

F:\myGitRepository\mavlink>python -m mavgenerate.py
C:\Python27\python.exe: No module named future

F:\myGitRepository\mavlink>python -m mavgenerate
Traceback (most recent call last):
  File "C:\Python27\lib\runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "C:\Python27\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "F:\myGitRepository\mavlink\mavgenerate.py", line 42, in <module>
    from pymavlink.generator import mavgen
  File "pymavlink\generator\mavgen.py", line 12, in <module>
    from future import standard_library
ImportError: No module named future

F:\myGitRepository\mavlink>

**Comment by wmx-github** [comment]
File "pymavlink\generator\mavgen.py", line 12,       (  from future import standard_library  )

**Comment by magicrub** [comment]
"ImportError: No module named future"
You need to install future. We're hearing a lot of people having trouble with this so we should look into the installation tool and see why it's not installing it correctly..

**Comment by amilcarlucas** [comment]
Not a bug.

IMHO this can be closed now.

**Comment by hamishwillee** [comment]
Future is not installed automatically. This PR will fix the docs  instructions to mention the requirement: https://github.com/mavlink/mavlink-devguide/pull/40
