### ISSUE TITLE
missing mission_type

### ISSUE THREAD

**Issue by starraiser** [mavlink/mavlink#690]
I have used the MAVLink Generator to generate java code, but there is no field of 'mission_type' in the java code while the xml file has field 'mission_type'. Did I miss some operation ?

**Comment by WickedShell** [comment]
mission_type is a MAVLink 2 extension of the message. Java doesn't understand MAVLink 2 at all, so you are limited to MAVLink 1 message ID's and features.

**Comment by starraiser** [comment]
Thanks for answering. I am working on coding mavlink protocol using lua, and I meet a lot of confusion. Maybe it is because of my poor English, haha
