### ISSUE TITLE
VIDEO_STREAM_INFORMATION lacks video Aspect Ratio

### ISSUE THREAD

**Issue by dogmaphobic** [mavlink/mavlink#766]
Is anybody already using this? It's marked as "WIP".

Can I add an aspect_ratio field to it or should I create a new pair of command/response just for it?

My idea is to just add this to the end of the message:

```
      <field type="float" name="aspect_ratio">Video image aspect ratio (width / height)</field>
```

**Comment by hamishwillee** [comment]
@dogmaphobic Bringing this back to your attention. I have no idea who is using this, but probably only QGC.

Perhaps the best way to test this is to just create a PR if you think this would be useful. Otherwise can we close this?

**Comment by dogmaphobic** [comment]
Nah, this would only be an issue for streams with non square pixels (anamorphic). I have yet to see one. In 99.9% of the cases, you can derive it from its frame size.

**Comment by ben-crowhurst** [comment]
Hey, I was looking to implement VIDEO_STREAM_INFORMATION as a way of getting available video feeds.  As @dogmaphobic noted in 2017 it was, and still is, marked as WIP.

Will this message ever get ratified and make it into the mainstream protocol?

**Comment by ben-crowhurst** [comment]
Sorry just noted I've hijacked a thread, I'll create separate issue.
