### ISSUE TITLE
Determine Flight Mode (custom_mode value)

### ISSUE THREAD

**Issue by Aurusd** [mavlink/mavlink#774]
I cant find flight modes description from mavlink message. Use intel aero drone. In heartbeat message received
base_mode = 81;
custom_mode = 84148224;
Where i can find description of this options to determine flight mode? Where can find custom_mode enum or possible values?

**Comment by dagar** [comment]
Unfortunately these have to be decoded per flight stack. For PX4 you can find them here. https://github.com/PX4/Firmware/blob/master/src/modules/commander/px4_custom_mode.h#L45

**Comment by amilcarlucas** [comment]
The ones from Ardupilot are now available in enums. Please use the latest version from master.

AFAIK this can be closed now.

**Comment by hamishwillee** [comment]
Agreed. Closing. Thanks
