### ISSUE TITLE
Code cleanup

### ISSUE THREAD

**Issue by wiseman** [mavlink/mavlink#78]
Would a pull request making the code [pep8](http://www.python.org/dev/peps/pep-0008/)-compliant be welcome?

It's always nice to work with nicely and uniformly formatted code. :)

**Comment by amilcarlucas** [comment]
Yes, such a PR would be welcomed. Most of the python code is in the upstream ardupilot/pymavlink repository. Please make your pull request here: https://github.com/ArduPilot/pymavlink/pulls

For the rest of the python code this repository is the correct one.

IMHO this one can be closed now

**Comment by hamishwillee** [comment]
Agreed. Thanks @amilcarlucas
