### ISSUE TITLE
False generation of mavlink headers (with bad XML input)

### ISSUE THREAD

**Issue by samacumen** [mavlink/mavlink#783]
I noticed incorrect .h header file generation while using mavgenerate.py with my custom XML file. The message when looks like the following generates incomplete/incorrect .h file 

```
<message id="500" name="TEST_MESSAGE">
	<field type="uint16_t" name="data1">Some data </field>
	<field type="uint16_t" name=""></field>
	<field type="uint16_t" name="data3"></field>
    </message> 
```

Please note the name for the 2nd field above is missing (**name=""**). The struct generated is:

```
MAVPACKED(
typedef struct __mavlink_test_message_t {
 uint16_t data1; /*< The number of packets received during */
 uint16_t ; /*< */
 uint16_t data3; /*< */
}) mavlink_test_message_t;
```

Intuitively, the user would assume the mavgenerate.py to throw an error. It took me a while to spot that the C compiler was unhappy about this silly error (I introduced when creating the XML), when the compiler was pointing at something entirely different.

**Comment by amilcarlucas** [comment]
This is a pymavlink issue. Please report it upstream at https://github.com/ardupilot/pymavlink/issues

**Comment by amilcarlucas** [comment]
@samacumen please do as I told you or it wont get fixed!

@hamishwillee This is a pymavlink issue that should be reported upstream to https://github.com/ardupilot/pymavlink/issues and closed here.

**Comment by samacumen** [comment]
Thanks, reported at pymavlink [here](https://github.com/ArduPilot/pymavlink/issues/150)

**Comment by hamishwillee** [comment]
Thanks guys. Closed.
