### ISSUE TITLE
Importing x25crc in Python implementation

### ISSUE THREAD

**Issue by jxltom** [mavlink/mavlink#797]
Currently, the python mavlink implementation generated by mavgenerator.py contains ```from ...generator.mavcrc import x25crc```.

I have to including mavcrc module manually to make the generated script running, is it better to including the ```x25crc``` module into the generated python implementation directly? In this way, the generated python implementation can run independently wihout any modification.

**Comment by amilcarlucas** [comment]
Please open a pull request rather than an issue. It is easier to discuss code modifications using a PR

**Comment by amilcarlucas** [comment]
This can IMHO be closed now

**Comment by hamishwillee** [comment]
@jxltom Do you think you could make this PR? I agree with @amilcarlucas that it would be best if you did this, but if not we should probably keep the issue open.

**Comment by jxltom** [comment]
I found that this is a upstream issue. So I made a PR in https://github.com/ArduPilot/pymavlink/pull/152. We can discuss the code there.

After that PR is merged, sync upstream and update submodule in this project will solve this problem.
