### ISSUE TITLE
compile /mavlink/example/linux/mavlink_udp.c

### ISSUE THREAD

**Issue by alexx600** [mavlink/mavlink#810]
it is said that i should compile file using 
gcc -std=c99 -I ../../include/common -o mavlink_udp mavlink_udp.c

the issue is that include/common is not avaible in this package

**Comment by hdino** [comment]
You have to generate the MAVLink files according to the [documentation](https://github.com/mavlink/mavlink#generating-language-specific-source-files) or download the generated files from [here](https://github.com/mavlink/c_library_v2).

**Comment by alexx600** [comment]
Thank You:)
