### ISSUE TITLE
Cursor on Target capability (CoT)

### ISSUE THREAD

**Issue by RohanKurane** [mavlink/mavlink#820]
Hi,

This is not the right place to open this issue (but probably the closest and most appropriate)

Does the Intel RTF support the CoT message exchange protocol ? CoT is a series of XML schemas to send to a UAV device and a response is sent back. Are there any UAVs besides Intel RTF that support this ?

**Comment by LorenzMeier** [comment]
No it doesn't. MAVLInk is the lingua franca in the drone size class of Aero and supported: https://mavlink.io/en/
