### ISSUE TITLE
Add "too many waypoints" error code in the mavlink spec

### ISSUE THREAD

**Issue by ghost** [mavlink/mavlink#822]
Hi all,

based on the discussions as at https://github.com/mavlink/qgroundcontrol/issues/5852 and https://github.com/ArduPilot/ardupilot/issues/7254
and @DonLakeFlyer 's suggesion (https://github.com/mavlink/qgroundcontrol/issues/5852#issuecomment-350487660) I open an issue here.

Kind regards,
Thorsten

**Comment by hamishwillee** [comment]
@DonLakeFlyer This sounds useful still. Any reason not to append to https://mavlink.io/en/messages/common.html#MAV_MISSION_RESULT ?

**Comment by DonLakeFlyer** [comment]
> Any reason not to append to

Not that I can think ok
