### ISSUE TITLE
What mode can I Disarm the Intel RTF in ?

### ISSUE THREAD

**Issue by RohanKurane** [mavlink/mavlink#829]
@zehortigoza @lucasdemarchi @DonLakeFlyer 

I arm and takeoff the Intel RTF in Loiter mode. 
Then I - 
1. Try to Disarm - but it says the mode in invalid
2. I change to Land mode and then try to disarm but it still says the mode in invalid. 

What mode(s) can I do a Disarm in ?  
What is the correct procedure - 
Arm and Takeoff  followed by Land and Disarm ? 

Is there a table that tells which modes can I Arm and Disarm in ?

**Comment by LorenzMeier** [comment]
Please report in PX4/Firmware. Thanks!
