### ISSUE TITLE
rc_raw_channel

### ISSUE THREAD

**Issue by zenuavsolutions** [mavlink/mavlink#836]
for remote control companions like raspberry it would be great to have 16 channels

**Comment by rodizio1** [comment]
Yeah, something similar to RC_CHANNELS_OVERRIDE but with 16 channels would be great.

**Comment by amilcarlucas** [comment]
[RC_CHANNELS](https://mavlink.io/en/messages/common.html#RC_CHANNELS) message already supports 18 channels
[RC_CHANNELS_OVERRIDE](https://mavlink.io/en/messages/common.html#RC_CHANNELS_OVERRIDE) message already supports 18 channels when using MAVLink 2.0
