### ISSUE TITLE
Links do not exist anymore. please correct.

### ISSUE THREAD

**Issue by samacumen** [mavlink/mavlink#850]
The link in some of the mavlink github page/QGC mavlink page do not work. e.g. 

1) on https://github.com/mavlink/mavlink/tree/master/examples/linux (no quickstart guide at this link, http://qgroundcontrol.org/dev/mavlink_linux_integration_tutorial)

2) message_definitions/v1.0/common.xml (http://qgroundcontrol.org/parameter_interface)

Please correct these and also in http://qgroundcontrol.org/mavlink/start many links lead no-where.

**Comment by hamishwillee** [comment]
@samacumen Thanks. 

>  https://github.com/mavlink/mavlink/tree/master/examples/linux (no quickstart guide at this link, http://qgroundcontrol.org/dev/mavlink_linux_integration_tutorial)

I have simply deleted the link from the document - there is no replacement: https://github.com/mavlink/mavlink/pull/851

> message_definitions/v1.0/common.xml (http://qgroundcontrol.org/parameter_interface)

I have fixed up all inks to point to the correct new site/documents
https://github.com/mavlink/mavlink/pull/852

> Please correct these and also in http://qgroundcontrol.org/mavlink/start many links lead no-where.

The old site on qgroundcontrol.org is dead - as it states on the home link up the top. The old site still has some old/broken links, but again, these should be ignored while we migrate materials (as it says up the top of the home page). The new site is: https://mavlink.io/en/

I'll let this closed, but the PRs should fix the problems in the coming days.

**Comment by samacumen** [comment]
Perfect. Thanks for your time on this.
