### ISSUE TITLE
Implementing MAVLink Protocol on MyRio

### ISSUE THREAD

**Issue by amvstore2018** [mavlink/mavlink#864]
Hi
I want to use MAVLink in my Autopilot.
I'm using myRio1900 board 
the only way i could use it is by converting the static library (c_library_v2)to shared library so that I can call it.
for more information -> http://www.ni.com/tutorial/14690/en/
I'm wondering if anybody could help me with that

**Comment by amilcarlucas** [comment]
This is a question, not a bug report. Please post it in the support forum instead.
