### ISSUE TITLE
Proper way to increase the rate of vehicle system mode messages

### ISSUE THREAD

**Issue by korigod** [mavlink/mavlink#871]
Sometimes you need to receive the vehicle system mode more often than once a second, which is often the default heartbeat interval. Is the increase in the heartbeat frequency the right way to address this? E.g. in PX4 Firmware heartbeat frequency is hard-coded. The only other message with mode in it is `HIGH_LATENCY`.

**Comment by dagar** [comment]
From a mavlink perspective I don't see why we can't send the HEARTBEAT at >= 1 Hz (MAV_CMD_SET_MESSAGE_INTERVAL).

Firmware HEARTBEAT is a constant 1Hz, but we could make it possible to increase.
