### ISSUE TITLE
Storage & Image capture information messages are marked as WIP

### ISSUE THREAD

**Issue by shakthi-prashanth-m** [mavlink/mavlink#874]
As discussed with @julianoes, MAVLink messages related to storage and image capture are marked as **WIP**; but they're being used by [DroneCore camera plugin](https://github.com/dronecore/DroneCore/pull/338/files/d6be938c26e0f31de9c57e37182997e397add0f7#diff-6029886b93401bf0054882a2cc199efdR32).

- http://mavlink.org/messages/common/#MAV_CMD_REQUEST_STORAGE_INFORMATION
- http://mavlink.org/messages/common/#STORAGE_INFORMATION
- http://mavlink.org/messages/common/#MAV_CMD_STORAGE_FORMAT
- http://mavlink.org/messages/common/#MAV_CMD_REQUEST_CAMERA_IMAGE_CAPTURE

If these messages works fine, then we need to remove "WIP".

**Comment by julianoes** [comment]
And we should actually remove the storage ID sand use different component IDs in the same way as it is done for the cameras.

**Comment by hamishwillee** [comment]
WIP has now been removed
