### ISSUE TITLE
mavlink_udp.c example testing and QGC behaviors

### ISSUE THREAD

**Issue by weiminshen99** [mavlink/mavlink#882]
When testing mavlink_udp.c with QGC, I noticed an interesting behavior:
Case 1: If QGC is already connected to another existing UAV, then messages sent from mavlink_udp.c will be displayed properly at QGC (e.g., you can see them in Mavlink Inspector).
Case 2: If QGC is freshly started with no previous connection, mavlink_udp.c will connect to QGC, but the messages sent from mavlink_udp.c are NOT displayed at QGC. One can tell that they are indeed connected, because mavlink_udp.c pop up with all the received messages from QGC.

Could someone please explain what I did wrong, or why this behavior is indeed normal? Thanks!

**Comment by hamishwillee** [comment]
Closing. No one has explained in this time, no one knows or sees it as concering enough to find out.
