### ISSUE TITLE
Reducing the size of packets

### ISSUE THREAD

**Issue by MatejHrlec** [mavlink/mavlink#891]
Greetings!
I am developing a communication protocol based on Mavlink. The problem is that the API I use limit's me to only send 100B at a time (upload speed is 1KB/s, download 8KB/s if that matters). And I was successful in sending a few messages already.

Are there any solutions in limiting the size of packets, perhaps by splitting them into more parts?

Thanks for any help.

**Comment by LorenzMeier** [comment]
Thats something your link should be doing (and almost every link we use does). Just split the packet, it will be correctly assembled at the other end because MAVLink parses the serial stream, rather than assuming packet bounds.

**Comment by MatejHrlec** [comment]
I apologize that I wasn't specific enough. The API I use only sends bytes, it does not provide any inherent support for Mavlink. I want to code that in myself.

So what I do, is take a Mavlink message, pack it into a byte array and send it over my link. Now the issue is that many message types are bigger than 100B when packed.
