### ISSUE TITLE
Splitting messages into smaller packets

### ISSUE THREAD

**Issue by MatejHrlec** [mavlink/mavlink#895]
Greetings!
I posted a similar question before, but it was closed prematurely. So this time I'll try to be more specific with my problem.

I am sending packets over a link, that can send/receive 100B at a time. This is done with the DJI Android API. This link has no inherent support for Mavlink, but I want to implement it in. Because of this limitations I cannot send messages that are bigger than 100B when packed. This link is also not loss-less. I am also making a custom Mavlink receiver on the drone's side.

One possible solution could perhaps be creating a new message definition, that would be exactly 100B big when packed. But then I'm not sure what fields it would need...
Or if there is a preexisting solution, I would also be grateful to know about it!

Thank you for any help.

**Comment by LorenzMeier** [comment]
It wasn't closed prematurely. MAVLink is a serial protocol. You can just fill your 100-byte buffer and take the data out of the link at the other end and MAVLink will take care of re-assembling the packets. Its using packets, but it is not assuming a packetized link. If your implementation is open source and available please share a link here as more people might be interested in it. Thanks!

**Comment by MatejHrlec** [comment]
Well, this work is part of my master thesis and I'm not sure if it will be open-source at the end?

Right now I basically parse my received bytes in a for loop with: mavlink::mavlink_parse_char(channelNum, oneByte, &mavlinkMsg, &mavlinkStatus);

And from what I'm looking at now in the Mavlink's source code, the channel number seems to take care of buffering the data. If this is true, this is a nice solution to my problem.
