### ISSUE TITLE
Implement MAVLink in a flight controller

### ISSUE THREAD

**Issue by hexagon-robotics** [mavlink/mavlink#896]
Hello!,

Can I use MAVLink on a flight controller where I work? With Open-source firmware (C/C++) and Open-source software configurator (Java).

Best regards,
Javier

**Comment by hamishwillee** [comment]
Yes. MAVLink is implemented on lots of flight controllers. Two popular popular open source flight stacks are [PX4](http://px4.io/) and [ArduPilot](http://ardupilot.org/). Follow those links for more information.
