### ISSUE TITLE
CRC bisection search fails if only one message is defined

### ISSUE THREAD

**Issue by ndepal** [mavlink/mavlink#905]
If `MAVLINK_MESSAGE_CRCS` has length 1, the bisection search in [mavlink_get_msg_entry](https://github.com/mavlink/c_library_v2/blob/master/mavlink_helpers.h#L491) looks at entry 1 of an array of size 1, i.e. beyond the array memory. This will cause decoding of that message to fail, even if the message is sent correctly.

This is only a problem if there is only one message defined so it will rarely, if ever, cause any issues but it's a bug nonetheless.

**Comment by amilcarlucas** [comment]
This is a pymavlink bug. Please report it upstream at ardupilot/pymavlink repository.
