### ISSUE TITLE
Templates for drones control

### ISSUE THREAD

**Issue by Omar-M-AbdelAziz** [mavlink/mavlink#930]
Hello, 

I have a drone with PIXHAWK, I want to use it to do specific tasks. 
However, I can't see a template for a ROS node or a guide for how to do simple tasks(e.g. flying in a square) 
Is there something like this ? 
I've read the developers' guide but I can't find what I am looking for

**Comment by TSC21** [comment]
@Omar-M-AbdelAziz you are probably looking for this if you are actually looking to use PX4: https://dev.px4.io/en/ros/mavros_offboard.html. For APM: http://ardupilot.org/dev/docs/ros.html. But this is all autopilot dependent, as Mavlink is a message marshalling library, so you are looking for help on the wrong issues list.
