### ISSUE TITLE
Melodic mavlink ROS package missing pymavlink

### ISSUE THREAD

**Issue by cberner** [mavlink/mavlink#931]
The latest ROS packages for melodic don't seem to include pymavlink, even though the wiki states that they do: http://wiki.ros.org/mavlink

This happened once before, so perhaps related: https://github.com/mavlink/mavlink/issues/553

Also, the wiki mentions rosdep `python-pymavlink`, but that doesn't exist anymore

**Comment by amilcarlucas** [comment]
Please report this upstream at Ardupilo/pymavlink
