### ISSUE TITLE
Can I get data like hae , ce and le from mavlink ? 

### ISSUE THREAD

**Issue by RohanKurane** [mavlink/mavlink#933]
@zehortigoza 
Are there mavlink commands to get UAV data such as 

hae = height above ellipsoid in meters
le = linear error in meters
ce = circular error in meters

Here is some explanation on each : 

The hae attribute denotes height above ellipsoid in meters. 

The ce attribute denotes the circular error, in meters, around the point defined by the lat and
lon attributes. 

The le attribute denotes the linear error, in meters, as a height range about the event point.

An event point is defined by lat and lon (which can be derived from MAVLINK)

**Comment by hamishwillee** [comment]
A "more" human-readable version of that spec [can be found here](https://mavlink.io/en/messages/common.html).  If the information is not present in that file then it may still be available in a specific dialect (see the files at the same level) used by a particular autopilot. Custom messages can also be added - but then you will need to create a dialect for the message and make the appropriate changes to process the message in the autopilot.
