### ISSUE TITLE
/usr/bin/python: No module named tools

### ISSUE THREAD

**Issue by gin2017** [mavlink/mavlink#943]
I have  git cloned the mavlink from github.
And then do some steps below to build the source code .
a. mkdir build && cd build
b. cmake  ..
c. make 
Then some questions has occured. Anyone can help me ? Thanks very much.
![image](https://user-images.githubusercontent.com/26371147/42358879-7e0537a0-8111-11e8-8285-4c0ac60e276d.png)

**Comment by gin2017** [comment]
Anyone can help me ???

**Comment by hamishwillee** [comment]
Docs on setup etc are here: https://mavlink.io/en/getting_started/

**Comment by pjalocha** [comment]
> git submodule update --init --recursive

This is an absolutely essential step - it must be mentioned in the README - other you walk around trying to solve issues, while nothing works.

**Comment by hamishwillee** [comment]
Does no one know how to read? This is covered in the manual. 

I guess the answer is no. I'll add a quick start.
