### ISSUE TITLE
WHat is the status of missionlib ?

### ISSUE THREAD

**Issue by hamishwillee** [mavlink/mavlink#954]
According to the (old) docs, [/mavlink/mavlink/missionlib](https://github.com/mavlink/mavlink/tree/master/missionlib) is:

> ## MAVLink Mission Library (missionlib)
> The MAVLink mission library is a reference implementation for the handling of waypoint, parameter and command messages. It allows to equip any robot or MAV quickly with the ability to store onboard missions, onboard floating point parameters and to execute commands.
>
>It is intended to simplify the adoption of the higher-level layers of the MAVLink communication protocol.

Sounds like a good idea to provide higher level APIs like this. However this looks very out of date. 
- Is that the case? 
- Do we want to keep it?
- If so, what needs to happen to bring it up to date?

**Comment by LorenzMeier** [comment]
I would delete it as hopelessly outdated.
