### ISSUE TITLE
Generated java code bug

### ISSUE THREAD

**Issue by lTBeL** [mavlink/mavlink#955]
Generated java code bug:
Line 147 at `com.MAVLink.MAVLinkPacket`
generateCRC method, line 155
`crc.update_checksum(len);`
Should be changed to: `crc.update_checksum(payloadSize);`

Otherwise the data crc sent will be wrong.

**Comment by amilcarlucas** [comment]
Please report this upstream in the ArduPilot/pymavlink repository
