### ISSUE TITLE
Outputs of PX4 PID Rate Controllers

### ISSUE THREAD

**Issue by Steplerchik** [mavlink/mavlink#996]
Hi,

I need to obtain data about **outputs** of PID Rate Controllers (for roll, pitch and yaw angles) from copter (PX4) with a help of mavlink.

Have you any thoughts?

**Comment by dagar** [comment]
Hi @Steplerchik 

Take a look at the `ACTUATOR_CONTROL_TARGET` message. https://mavlink.io/en/messages/common.html#ACTUATOR_CONTROL_TARGET

Actuator controls is the output of the PX4 rate controller (roll = 0, pitch = 1, yaw = 1, throttle = 1).
